### ISSUE TITLE
User Notification Settings crashes

### ISSUE THREAD

**Issue by jardakotesovec** [pkp/pkp-lib#10698]
**Describe the bug**
User Notification settings screen does not show up and php generate exception

**To Reproduce**
1) Login
2) Click on the user icon in top right corner
3) Click on Edit Profile
4) Click on Notifications

**Expected** : Notifications to be displayed.
**Actual** : Nothing shows up.. and there is crash in PHP log

**What application are you using?**
 OJS, OMP or OPS version 3.5

**Additional information**
```
[Thu Dec 12 17:45:29 2024] [::1]:59701 [500]: GET /index.php/publicknowledge/$$$call$$$/tab/user/profile-tab/notification-settings?_=1734021928247 - Uncaught Exception: FBV: Element ID not set in /Users/jarda/git/pkp/pkp-main/ojs-main/lib/pkp/classes/form/FormBuilderVocabulary.php:261
Stack trace:
#0 /Users/jarda/git/pkp/pkp-main/ojs-main/cache/t_compile/8d17b592863b957b556b756034f0e2fe7d932aef^a30f866b29d80531bfc63eba879304b1f665a133_0.app.usernotificationSettingsForm.tpl.php(121): PKP\form\FormBuilderVocabulary->smartyFBVElement(Array, Object(Smarty_Internal_Template))
#1 /Users/jarda/git/pkp/pkp-main/ojs-main/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_675b132983d613_41173813(Object(Smarty_Internal_Template))
#2 /Users/jarda/git/pkp/pkp-main/ojs-main/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))
#3 /Users/jarda/git/pkp/pkp-main/ojs-main/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(217): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template))
#4 /Users/jarda/git/pkp/pkp-main/ojs-main/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(238): Smarty_Internal_Template->render(false, 0)
#5 /Users/jarda/git/pkp/pkp-main/ojs-main/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(116): Smarty_Internal_TemplateBase->_execute(Object(Smarty_Internal_Template), NULL, '8d17b592863b957...', NULL, 0)
#6 /Users/jarda/git/pkp/pkp-main/ojs-main/lib/pkp/classes/template/PKPTemplateManager.php(1253): Smarty_Internal_TemplateBase->fetch('user/notificati...', NULL, '8d17b592863b957...', NULL)
#7 /Users/jarda/git/pkp/pkp-main/ojs-main/lib/pkp/classes/form/Form.php(217): PKP\template\PKPTemplateManager->fetch('user/notificati...')
#8 /Users/jarda/git/pkp/pkp-main/ojs-main/lib/pkp/classes/notification/form/PKPNotificationSettingsForm.php(135): PKP\form\Form->fetch(Object(APP\core\Request), NULL, false)
#9 /Users/jarda/git/pkp/pkp-main/ojs-main/lib/pkp/controllers/tab/user/ProfileTabHandler.php(357): PKP\notification\form\PKPNotificationSettingsForm->fetch(Object(APP\core\Request))
#10 [internal function]: PKP\controllers\tab\user\ProfileTabHandler->notificationSettings(Array, Object(APP\core\Request))
#11 /Users/jarda/git/pkp/pkp-main/ojs-main/lib/pkp/classes/core/PKPRouter.php(329): call_user_func(Array, Array, Object(APP\core\Request))
#12 /Users/jarda/git/pkp/pkp-main/ojs-main/lib/pkp/classes/core/PKPComponentRouter.php(265): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array)
#13 /Users/jarda/git/pkp/pkp-main/ojs-main/lib/pkp/classes/core/Dispatcher.php(158): PKP\core\PKPComponentRouter->route(Object(APP\core\Request))
#14 /Users/jarda/git/pkp/pkp-main/ojs-main/lib/pkp/classes/core/PKPApplication.php(395): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#15 /Users/jarda/git/pkp/pkp-main/ojs-main/index.php(30): PKP\core\PKPApplication->execute()
#16 {main}
  thrown in /Users/jarda/git/pkp/pkp-main/ojs-main/lib/pkp/classes/form/FormBuilderVocabulary.php on line 261
```

**Comment by asmecher** [comment]
Fixed!

**Comment by touhidurabir** [comment]
@asmecher it seems the problem still persist , please check the PRs below 

[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/10757
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/4575 [TEST ONLY]

**Comment by asmecher** [comment]
@touhidurabir, that PR masks the error, but doesn't fix the cause. I've fixed it [here](https://github.com/pkp/ojs/commit/de0da4acfd19e8640ed777930f8beb060fc309c9).
