### ISSUE TITLE
Upgrade from OJS 3.4.0-8 to OJS 3.5.0rc2

### ISSUE THREAD

**Issue by shantanu198713** [pkp/pkp-lib#11194]
### Valid Title

- [x] I have updated the title to accurately reflect the bug description

### Description

PHP-8.3.14
MYSQL-9.1

I attempted to upgrade from **OJS 3.4.0-8** to **OJS 3.5.0rc2**, but the process failed due to the following error. The upgrade could not be completed successfully, and troubleshooting is required to identify and resolve the issue.

### Steps to Reproduce

I attempted to upgrade from OJS 3.4.0-8 to OJS 3.5.0rc2.

### Expected Result

Continue to upgrade.

### Actual Result

Upgradation failed.

### Application Version

OJS-3.5.0rc2

### Logs

```
PHP Fatal error:  Uncaught TypeError: PKP\invitation\core\Invitation::initialize(): Argument #2 ($contextId) must be of type ?int, string given, called in H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\classes\migration\upgrade\v3_5_0\I9197_MigrateAccessKeys.php on line 92 and defined in H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\classes\invitation\core\Invitation.php:112
Stack trace:
#0 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\classes\migration\upgrade\v3_5_0\I9197_MigrateAccessKeys.php(92): PKP\invitation\core\Invitation->initialize(45, 'MailListContext', NULL, NULL)
#1 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\classes\install\Installer.php(444): PKP\migration\upgrade\v3_5_0\I9197_MigrateAccessKeys->up()
#2 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\classes\install\Installer.php(297): PKP\install\Installer->executeAction(Array)
#3 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\classes\install\Installer.php(206): PKP\install\Installer->executeInstaller()
#4 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\classes\install\form\UpgradeForm.php(49): PKP\install\Installer->execute()
#5 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\pages\install\InstallHandler.php(148): PKP\install\form\UpgradeForm->execute()
#6 [internal function]: PKP\pages\install\InstallHandler->installUpgrade(Array, Object(APP\core\Request))
#7 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\classes\core\PKPRouter.php(327): call_user_func(Array, Array, Object(APP\core\Request))
#8 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\classes\core\PKPPageRouter.php(249): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array, false)
#9 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\classes\core\Dispatcher.php(157): PKP\core\PKPPageRouter->route(Object(APP\core\Request))
#10 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\classes\core\PKPApplication.php(422): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#11 H:\wamp64\www\ojs-3.5.0rc2\index.php(21): PKP\core\PKPApplication->execute()
#12 {main}
  thrown in H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\classes\invitation\core\Invitation.php on line 112
```

### Additional Information

![Image](https://github.com/user-attachments/assets/7f9c27f0-a04e-45e5-b2f0-53abd5307cec)

---
**PRs**

🗂 Branch: stable-3_5_0
──────────────────────────────
✅ pkp-lib: #11210 (**MERGED**)
🧪 ~~OJS: pkp/ojs#4795 (TESTS ONLY)~~

✅ pkp-lib: #11217 (**MERGED**)
🧪 ~~OJS: pkp/ojs#4805 (TESTS ONLY)~~

✅ pkp-lib: https://github.com/pkp/pkp-lib/pull/11234
🧪 OJS: https://github.com/pkp/ojs/pull/4816 (TESTS ONLY)

🗂 Branch: main
──────────────────────────────
✅ pkp-lib: #11211 (**MERGED**)
🧪 ~~OJS: pkp/ojs#4796 (TESTS ONLY)~~

✅ pkp-lib: #11218 (**MERGED**)

✅ pkp-lib: https://github.com/pkp/pkp-lib/pull/11235
🧪 OJS: https://github.com/pkp/ojs/pull/4817 (TESTS ONLY)

**Comment by shantanu198713** [comment]
Hi @kaitlinnewson kindly guide me for above error so that I can continue further Upgradation test.

**Comment by kaitlinnewson** [comment]
Hi @defstat, are you able to take a look at this one? It looks to be an issue with a migration related to the invitations work.

**Comment by defstat** [comment]
@shantanu198713 Thanks for reporting this. From the logs you posted, it looks like the `access_key` that's causing the upgrade issue is of type `'MailListContext'`. Do you know which feature in your installation might be generating this type of access key? Also, could you check if it’s already expired? It might be coming from a plugin you're using or possibly leftover data from a previous migration?

In any case, I’ve added a proposed solution in the [description comment](https://github.com/pkp/pkp-lib/issues/11194#issue-2955135617) of this issue. You're welcome to try it out on your installation if you'd like.

@asmecher Do you have some time to review it?

**Comment by shantanu198713** [comment]
Hi @defstat @asmecher @kaitlinnewson 

Thank you for your response.

I have applied the patches mentioned above, and the `access_key` error has been resolved. However, I am now encountering a new error during the upgrade process, which is mentioned below.

Could you please guide me on resolving this error and proceeding with further upgrade testing?

**Error Log**
```
2025-04-01 09:27:13 [downgrade for "PKP\migration\upgrade\v3_5_0\I9771_OrcidMigration" unsupported: Downgrade not supported]
ERROR: Upgrade failed: DB: PDOException: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`ojs`.`publications`, CONSTRAINT `publications_issue_id_foreign` FOREIGN KEY (`issue_id`) REFERENCES `issues` (`issue_id`) ON DELETE SET NULL) in H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\lib\vendor\laravel\framework\src\Illuminate\Database\Connection.php:571
Stack trace:
#0 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\lib\vendor\laravel\framework\src\Illuminate\Database\Connection.php(571): PDOStatement->execute()
#1 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\lib\vendor\laravel\framework\src\Illuminate\Database\Connection.php(812): Illuminate\Database\Connection->Illuminate\Database\{closure}('\n              ...', Array)
#2 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\lib\vendor\laravel\framework\src\Illuminate\Database\Connection.php(779): Illuminate\Database\Connection->runQueryCallback('\n              ...', Array, Object(Closure))
#3 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\lib\vendor\laravel\framework\src\Illuminate\Database\Connection.php(560): Illuminate\Database\Connection->run('\n              ...', Array, Object(Closure))
#4 H:\wamp64\www\ojs-3.5.0rc2\classes\migration\upgrade\v3_5_0\I10157_CreateAndMigrateIssueIdField.php(48): Illuminate\Database\Connection->statement('\n              ...')
#5 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\classes\install\Installer.php(444): APP\migration\upgrade\v3_5_0\I10157_CreateAndMigrateIssueIdField->up()
#6 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\classes\install\Installer.php(297): PKP\install\Installer->executeAction(Array)
#7 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\classes\install\Installer.php(206): PKP\install\Installer->executeInstaller()
#8 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\classes\cliTool\UpgradeTool.php(97): PKP\install\Installer->execute()
#9 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\classes\cliTool\UpgradeTool.php(70): PKP\cliTool\UpgradeTool->upgrade()
#10 H:\wamp64\www\ojs-3.5.0rc2\tools\upgrade.php(22): PKP\cliTool\UpgradeTool->execute()
#11 {main}

Next Illuminate\Database\QueryException: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`ojs`.`publications`, CONSTRAINT `publications_issue_id_foreign` FOREIGN KEY (`issue_id`) REFERENCES `issues` (`issue_id`) ON DELETE SET NULL) (Connection: mysql, SQL:
                    UPDATE publications p
                    JOIN publication_settings ps
                        ON p.publication_id = ps.publication_id
                        AND ps.setting_name = 'issueId'
                    SET p.issue_id = ps.setting_value
                ) in H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\lib\vendor\laravel\framework\src\Illuminate\Database\Connection.php:825
Stack trace:
#0 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\lib\vendor\laravel\framework\src\Illuminate\Database\Connection.php(779): Illuminate\Database\Connection->runQueryCallback('\n              ...', Array, Object(Closure))
#1 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\lib\vendor\laravel\framework\src\Illuminate\Database\Connection.php(560): Illuminate\Database\Connection->run('\n              ...', Array, Object(Closure))
#2 H:\wamp64\www\ojs-3.5.0rc2\classes\migration\upgrade\v3_5_0\I10157_CreateAndMigrateIssueIdField.php(48): Illuminate\Database\Connection->statement('\n              ...')
#3 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\classes\install\Installer.php(444): APP\migration\upgrade\v3_5_0\I10157_CreateAndMigrateIssueIdField->up()
#4 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\classes\install\Installer.php(297): PKP\install\Installer->executeAction(Array)
#5 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\classes\install\Installer.php(206): PKP\install\Installer->executeInstaller()
#6 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\classes\cliTool\UpgradeTool.php(97): PKP\install\Installer->execute()
#7 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\classes\cliTool\UpgradeTool.php(70): PKP\cliTool\UpgradeTool->upgrade()
#8 H:\wamp64\www\ojs-3.5.0rc2\tools\upgrade.php(22): PKP\cliTool\UpgradeTool->execute()
#9 {main}
```
![Image](https://github.com/user-attachments/assets/1b63db61-d664-4da6-9cb3-edcbc3c87630)

### Database Structure Screenshot for reference

 **Publications Table**
![Image](https://github.com/user-attachments/assets/4f4fcc3e-65cc-4871-9ee2-1cd74616e752)

**Issues Table**
![Image](https://github.com/user-attachments/assets/10be381e-2929-4955-8342-a07159595dde)

**Comment by shantanu198713** [comment]
I checked the `access_keys` table and found 96 rows with an `expiry_date` set to 2038, where the `context` is set to `MailListContext`. Given this, is it safe to manually delete these rows from the table?

![Image](https://github.com/user-attachments/assets/67732127-df7f-420c-85f6-7e01c7fb4d99)

**Comment by defstat** [comment]
> I checked the `access_keys` table and found 96 rows with an `expiry_date` set to 2038, where the `context` is set to `MailListContext`. Given this, is it safe to manually delete these rows from the table?
> 
> ![Image](https://github.com/user-attachments/assets/67732127-df7f-420c-85f6-7e01c7fb4d99)

@shantanu198713 even though the patch for the invitations will handle those cases, yes, removing them will also solve your initial issue. 

The issue that you are reporting [here](https://github.com/pkp/pkp-lib/issues/11194#issuecomment-2768074553) seems to be a different one though, unrelated to the initial one. 

It seems that it is related to publications that are related to specific issueIds that are not present, anymore, in your DB's installation

You can check if this is the case by running the following query on the `3.4.0-8` DB

```
select * from  
(
    select * from publication_settings 
    where setting_name = 'issueId'
) a
left outer join issues b on b.issue_id = a.setting_value 
where b.issue_id is null
```

If any rows appear, that would probably mean that there are publications assigned to issues that are not present.

**Comment by shantanu198713** [comment]
Hi @defstat 

As suggested, we found 97 rows where `issue_id` is NULL. Can we proceed with cleaning up these records, or do you recommend any further actions?

![Image](https://github.com/user-attachments/assets/e3f82d5b-7817-4b19-9132-0ff4374a6d6a)

**Comment by bozana** [comment]
Hi @defstat and @shantanu198713 ,

It is strange that 'issueId' is 0. I am wondering how that comes... 🤔 
It seems like this PreflightCheck code (https://github.com/pkp/ojs/blob/stable-3_4_0/classes/migration/upgrade/v3_4_0/PreflightCheckMigration.php#L232) was not executed when you were upgrading to 3.4.0 🤔 
So yes, @shantanu198713 please double check everything -- if those publications should really not have any issue ID, if they should not be assigned to an issue, and if others have correct issue ID (but this I suppose it correct, else the editors will already complain :-)). 
If everything is correct, you can delete those entries from the publication_settings table, where issueId is 0. Double check everything is correct after the change.
Also, as Dimitris said, before doing any change, please backup everything!

**Comment by shantanu198713** [comment]
Hi @defstat @bozana 

As suggested, I checked and found that some articles were not scheduled and remained unassigned to an issue. I manually deleted them and attempted the upgrade again, which allowed it to proceed further.

**However, we have now encountered a new error, as mentioned below:**

```
[01-Apr-2025 17:05:50 Asia/Kolkata] PHP Fatal error:  Uncaught Error: Call to a member function getFullName() on null in H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\classes\migration\upgrade\v3_5_0\I10362_EventLogEditorNames.php:49
Stack trace:
#0 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\classes\install\Installer.php(444): PKP\migration\upgrade\v3_5_0\I10362_EventLogEditorNames->up()
#1 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\classes\install\Installer.php(297): PKP\install\Installer->executeAction(Array)
#2 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\classes\install\Installer.php(206): PKP\install\Installer->executeInstaller()
#3 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\classes\cliTool\UpgradeTool.php(97): PKP\install\Installer->execute()
#4 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\classes\cliTool\UpgradeTool.php(70): PKP\cliTool\UpgradeTool->upgrade()
#5 H:\wamp64\www\ojs-3.5.0rc2\tools\upgrade.php(22): PKP\cliTool\UpgradeTool->execute()
#6 {main}
  thrown in H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\classes\migration\upgrade\v3_5_0\I10362_EventLogEditorNames.php on line 49
``` 

![Image](https://github.com/user-attachments/assets/d176dd0e-169f-484b-823c-dad01419fc7f)

**Comment by defstat** [comment]
> Hi [@defstat](https://github.com/defstat) [@bozana](https://github.com/bozana)
> 
> I checked and found that some articles were not scheduled, remained unassigned to an issue, and were not important. I manually deleted them and attempted the upgrade again, which allowed it to proceed further.
> 
> **However, we have now encountered a new error, as mentioned below:**
> 
> ```
> [01-Apr-2025 17:05:50 Asia/Kolkata] PHP Fatal error:  Uncaught Error: Call to a member function getFullName() on null in H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\classes\migration\upgrade\v3_5_0\I10362_EventLogEditorNames.php:49
> Stack trace:
> #0 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\classes\install\Installer.php(444): PKP\migration\upgrade\v3_5_0\I10362_EventLogEditorNames->up()
> #1 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\classes\install\Installer.php(297): PKP\install\Installer->executeAction(Array)
> #2 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\classes\install\Installer.php(206): PKP\install\Installer->executeInstaller()
> #3 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\classes\cliTool\UpgradeTool.php(97): PKP\install\Installer->execute()
> #4 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\classes\cliTool\UpgradeTool.php(70): PKP\cliTool\UpgradeTool->upgrade()
> #5 H:\wamp64\www\ojs-3.5.0rc2\tools\upgrade.php(22): PKP\cliTool\UpgradeTool->execute()
> #6 {main}
>   thrown in H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\classes\migration\upgrade\v3_5_0\I10362_EventLogEditorNames.php on line 49
> ```

@kaitlinnewson can you check this last one?

**Comment by kaitlinnewson** [comment]
Hi @shantanu198713, can you try applying [this change](https://github.com/pkp/pkp-lib/pull/11217/files) and see if you can now continue the migration?

**Comment by shantanu198713** [comment]
Hi @kaitlinnewson, Thanks for the guidance.

I applied the fix as suggested and it proceeded successfully.

Now, we encountered a new issue: _`SQLSTATE[HY000]: General error: 1390 Prepared statement contains too many placeholders.`_

The error suggests that the SQL query being executed exceeds the permissible limit `(max_allowed_packet=64M)` for placeholders in a prepared statement. To address this, I will increase `max_allowed_packet to 320M` and observe the outcome. I will provide an update accordingly.

**Bellow is log**
```
2025-04-03 09:12:10 [migration: PKP\migration\upgrade\v3_5_0\COA75_AddUserRoleEndEmail]
2025-04-03 09:12:10 [migration: PKP\migration\upgrade\v3_5_0\I10738_RemoveInvalidUserGroups]
2025-04-03 09:12:10 [migration: PKP\migration\upgrade\v3_5_0\I10362_EventLogEditorNames]
2025-04-03 09:13:39 [revert migration: PKP\migration\upgrade\v3_5_0\I10738_RemoveInvalidUserGroups]
2025-04-03 09:13:39 [revert migration: PKP\migration\upgrade\v3_5_0\COA75_AddUserRoleEndEmail]
2025-04-03 09:13:39 [downgrade for "PKP\migration\upgrade\v3_5_0\COA75_AddUserRoleEndEmail" unsupported: Downgrade not supported]
ERROR: Upgrade failed: DB: PDOException: SQLSTATE[HY000]: General error: 1390 Prepared statement contains too many placeholders in H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\lib\vendor\laravel\framework\src\Illuminate\Database\MySqlConnection.php:47
Stack trace:
#0 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\lib\vendor\laravel\framework\src\Illuminate\Database\MySqlConnection.php(47): PDO->prepare('insert into `ev...')
#1 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\lib\vendor\laravel\framework\src\Illuminate\Database\Connection.php(812): Illuminate\Database\MySqlConnection->Illuminate\Database\{closure}('insert into `ev...', Array)
#2 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\lib\vendor\laravel\framework\src\Illuminate\Database\Connection.php(779): Illuminate\Database\Connection->runQueryCallback('insert into `ev...', Array, Object(Closure))
#3 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\lib\vendor\laravel\framework\src\Illuminate\Database\MySqlConnection.php(42): Illuminate\Database\Connection->run('insert into `ev...', Array, Object(Closure))
#4 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\lib\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(3717): Illuminate\Database\MySqlConnection->insert('insert into `ev...', Array)
#5 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\classes\migration\upgrade\v3_5_0\I10362_EventLogEditorNames.php(64): Illuminate\Database\Query\Builder->insert(Array)
#6 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\classes\install\Installer.php(444): PKP\migration\upgrade\v3_5_0\I10362_EventLogEditorNames->up()
#7 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\classes\install\Installer.php(297): PKP\install\Installer->executeAction(Array)
#8 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\classes\install\Installer.php(206): PKP\install\Installer->executeInstaller()
#9 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\classes\cliTool\UpgradeTool.php(97): PKP\install\Installer->execute()
#10 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\classes\cliTool\UpgradeTool.php(70): PKP\cliTool\UpgradeTool->upgrade()
#11 H:\wamp64\www\ojs-3.5.0rc2\tools\upgrade.php(22): PKP\cliTool\UpgradeTool->execute()
#12 {main}

Next Illuminate\Database\QueryException: SQLSTATE[HY000]: General error: 1390 Prepared statement contains too many placeholders (Connection: mysql, SQL: insert into `event_log_settings` (`locale`, `log_id`, `setting_name`, `setting_value`) values (, 2, editorName, IARJ Admin), (, 12, editorName, IARJ Admin), (, 16, editorName, IARJ Admin), (, 20, editorName, IARJ Admin), (, 24, editorName, IARJ Admin), (, 28, editorName, IARJ Admin), (, 66, editorName, IARJ Admin), (, 70, editorName, IARJ Admin), (, 74, editorName, IARJ Admin), (, 78, editorName, IARJ Admin), (, 82, editorName, IARJ Admin), (, 86, editorName, IARJ Admin), (, 90, editorName, IARJ Admin), ..............................................................................................................................(, 1459908, editorName, Editor IJAnS), (, 1459909, editorName, Editor IJAnS), (, 1460031, editorName, Chandra S. Nuthalapati), (, 1460123, editorName, Prem Lal Kashyap), (, 1460189, editorName, Prem Lal Kashyap), (, 1460193, editorName, Prem Lal Kashyap)) in H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\lib\vendor\laravel\framework\src\Illuminate\Database\Connection.php:825
Stack trace:
#0 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\lib\vendor\laravel\framework\src\Illuminate\Database\Connection.php(779): Illuminate\Database\Connection->runQueryCallback('insert into `ev...', Array, Object(Closure))
#1 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\lib\vendor\laravel\framework\src\Illuminate\Database\MySqlConnection.php(42): Illuminate\Database\Connection->run('insert into `ev...', Array, Object(Closure))
#2 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\lib\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(3717): Illuminate\Database\MySqlConnection->insert('insert into `ev...', Array)
#3 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\classes\migration\upgrade\v3_5_0\I10362_EventLogEditorNames.php(64): Illuminate\Database\Query\Builder->insert(Array)
#4 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\classes\install\Installer.php(444): PKP\migration\upgrade\v3_5_0\I10362_EventLogEditorNames->up()
#5 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\classes\install\Installer.php(297): PKP\install\Installer->executeAction(Array)
#6 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\classes\install\Installer.php(206): PKP\install\Installer->executeInstaller()
#7 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\classes\cliTool\UpgradeTool.php(97): PKP\install\Installer->execute()
#8 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\classes\cliTool\UpgradeTool.php(70): PKP\cliTool\UpgradeTool->upgrade()
#9 H:\wamp64\www\ojs-3.5.0rc2\tools\upgrade.php(22): PKP\cliTool\UpgradeTool->execute()
#10 {main}

H:\wamp64\www\ojs-3.5.0rc2>
```

**Comment by shantanu198713** [comment]
Hi @kaitlinnewson 

I have increased `max_allowed_packet to 320M` but am still encountering the [same issue as mentioned above](https://github.com/pkp/pkp-lib/issues/11194#issuecomment-2774449086). Could you please check and guide me on the next steps?

**Comment by kaitlinnewson** [comment]
Hi @shantanu198713, I've made [an additional change here](https://github.com/pkp/pkp-lib/pull/11217/files), could you try applying that and see if it resolves the issue for you?

**Comment by asmecher** [comment]
@kaitlinnewson, I think the issue is that the number of variable bindings in the query will scale with the data size, so with a big enough OJS database eventually any upgrade will error. This can be resolved by chunking the inserts: https://stackoverflow.com/a/57238745

**Comment by shantanu198713** [comment]
Hi @kaitlinnewson, Thanks for the guidance.

I applied the fix as suggested and it proceeded successfully.

Now, we encountered a new issue: `DB: PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '110--name' for key 'controlled_vocab_entry_settings.c_v_e_s_pkey' in`.

```
2025-04-04 09:03:51 [migration: PKP\migration\upgrade\v3_5_0\I10362_EventLogEditorNames]
2025-04-04 09:04:37 [migration: PKP\migration\upgrade\v3_5_0\I10292_RemoveControlledVocabEntrySettingType]
2025-04-04 09:04:37 [migration: PKP\migration\upgrade\v3_5_0\I10292_UpdateControlledVocabAssocId]
2025-04-04 09:04:48 [migration: PKP\migration\upgrade\v3_5_0\I10292_UpdateControlledVocabEntrySettingName]
2025-04-04 09:04:48 [revert migration: PKP\migration\upgrade\v3_5_0\I10292_UpdateControlledVocabAssocId]
2025-04-04 09:04:57 [revert migration: PKP\migration\upgrade\v3_5_0\I10292_RemoveControlledVocabEntrySettingType]
2025-04-04 09:04:57 [revert migration: PKP\migration\upgrade\v3_5_0\I10362_EventLogEditorNames]
2025-04-04 09:04:57 [downgrade for "PKP\migration\upgrade\v3_5_0\I10362_EventLogEditorNames" unsupported: Downgrade not supported]
ERROR: Upgrade failed: DB: PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '110--name' for key 'controlled_vocab_entry_settings.c_v_e_s_pkey' in H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\lib\vendor\laravel\framework\src\Illuminate\Database\Connection.php:596
Stack trace:
#0 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\lib\vendor\laravel\framework\src\Illuminate\Database\Connection.php(596): PDOStatement->execute()
#1 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\lib\vendor\laravel\framework\src\Illuminate\Database\Connection.php(812): Illuminate\Database\Connection->Illuminate\Database\{closure}('update `control...', Array)
#2 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\lib\vendor\laravel\framework\src\Illuminate\Database\Connection.php(779): Illuminate\Database\Connection->runQueryCallback('update `control...', Array, Object(Closure))
#3 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\lib\vendor\laravel\framework\src\Illuminate\Database\Connection.php(584): Illuminate\Database\Connection->run('update `control...', Array, Object(Closure))
#4 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\lib\vendor\laravel\framework\src\Illuminate\Database\Connection.php(536): Illuminate\Database\Connection->affectingStatement('update `control...', Array)
#5 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\lib\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(3830): Illuminate\Database\Connection->update('update `control...', Array)
#6 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\classes\migration\upgrade\v3_5_0\I10292_UpdateControlledVocabEntrySettingName.php(29): Illuminate\Database\Query\Builder->update(Object(Illuminate\Support\Collection))
#7 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\classes\install\Installer.php(444): PKP\migration\upgrade\v3_5_0\I10292_UpdateControlledVocabEntrySettingName->up()
#8 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\classes\install\Installer.php(297): PKP\install\Installer->executeAction(Array)
#9 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\classes\install\Installer.php(206): PKP\install\Installer->executeInstaller()
#10 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\classes\cliTool\UpgradeTool.php(97): PKP\install\Installer->execute()
#11 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\classes\cliTool\UpgradeTool.php(70): PKP\cliTool\UpgradeTool->upgrade()
#12 H:\wamp64\www\ojs-3.5.0rc2\tools\upgrade.php(22): PKP\cliTool\UpgradeTool->execute()
#13 {main}

Next Illuminate\Database\UniqueConstraintViolationException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '110--name' for key 'controlled_vocab_entry_settings.c_v_e_s_pkey' (Connection: mysql, SQL: update `controlled_vocab_entry_settings` set `setting_name` = name) in H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\lib\vendor\laravel\framework\src\Illuminate\Database\Connection.php:820
Stack trace:
#0 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\lib\vendor\laravel\framework\src\Illuminate\Database\Connection.php(779): Illuminate\Database\Connection->runQueryCallback('update `control...', Array, Object(Closure))
#1 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\lib\vendor\laravel\framework\src\Illuminate\Database\Connection.php(584): Illuminate\Database\Connection->run('update `control...', Array, Object(Closure))
#2 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\lib\vendor\laravel\framework\src\Illuminate\Database\Connection.php(536): Illuminate\Database\Connection->affectingStatement('update `control...', Array)
#3 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\lib\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(3830): Illuminate\Database\Connection->update('update `control...', Array)
#4 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\classes\migration\upgrade\v3_5_0\I10292_UpdateControlledVocabEntrySettingName.php(29): Illuminate\Database\Query\Builder->update(Object(Illuminate\Support\Collection))
#5 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\classes\install\Installer.php(444): PKP\migration\upgrade\v3_5_0\I10292_UpdateControlledVocabEntrySettingName->up()
#6 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\classes\install\Installer.php(297): PKP\install\Installer->executeAction(Array)
#7 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\classes\install\Installer.php(206): PKP\install\Installer->executeInstaller()
#8 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\classes\cliTool\UpgradeTool.php(97): PKP\install\Installer->execute()
#9 H:\wamp64\www\ojs-3.5.0rc2\lib\pkp\classes\cliTool\UpgradeTool.php(70): PKP\cliTool\UpgradeTool->upgrade()
#10 H:\wamp64\www\ojs-3.5.0rc2\tools\upgrade.php(22): PKP\cliTool\UpgradeTool->execute()
#11 {main}

H:\wamp64\www\ojs-3.5.0rc2>
```

**Comment by touhidurabir** [comment]
Hi @shantanu198713 , for the upgrade issue `DB: PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '110--name' for key 'controlled_vocab_entry_settings.c_v_e_s_pkey`, I am wondering how you end up with same combination of `controlled_vocab_entry_id-locale` as there should not be a case (if I am not mistaken) as multiple entry of same combination of these 2 columns should not get in the `controlled_vocab_entry_settings` table . 

can you please run the following sql and share the result
```sql
select * from `controlled_vocab_entries` as `cve` left join `controlled_vocab_entry_settings` as `cves` on `cves`.`controlled_vocab_entry_id` = `cve`.`controlled_vocab_entry_id` left join `controlled_vocabs` as `cv` on `cv`.`controlled_vocab_id` = `cve`.`controlled_vocab_id` where `cve`.`controlled_vocab_entry_id` = 110
```
given that form your error , it seems the `controlled_vocab_entry_id` is `110` . 

I do have one alternative approach at [here](https://github.com/pkp/pkp-lib/pull/11233/files) but I don't think that is the right solution here . I feel like somehow duplicate entry has entered into the `controlled_vocab_entry_settings` or `controlled_vocab_entries` table .

**Comment by touhidurabir** [comment]
Hi @shantanu198713 , thanks for sharing the sql query result . I am really wondering from where there `mods34-...` like `symbolics` get into the system as we only have following symbolics in the system 
```
submissionAgency
submissionDiscipline
submissionKeyword
submissionLanguage
submissionSubject
interest
```
and added some support to add more from 3.5+ . Are your installation using some third party plugin or something like that which is making changes to controlled vocabs ? Can you take a look at that . 

> I have applied the [suggested](https://github.com/pkp/pkp-lib/pull/11233/files) fix but still getting the same problem.

Perhaps it's not being applied properly as I can test and it works . But this is not the solution we should go for and that why I mentioned `dont apply it yet` . Instead of this approach , can you update the `up` method of `I10292_UpdateControlledVocabEntrySettingName.php` with following content and see if this resolve the issue . 

```php
DB::table("controlled_vocab_entry_settings")
    ->whereIn("setting_name", [
        "submissionAgency",
        "submissionDiscipline",
        "submissionKeyword",
        "submissionLanguage",
        "submissionSubject",
        "interest"
    ])
    ->update(["setting_name" => "name"]);
```

I personally think this will be a better approach .

**Comment by shantanu198713** [comment]
Hi @touhidurabir @asmecher @defstat @kaitlinnewson @bozana Thanks for the guidance.

As suggested by @touhidurabir, I applied the recommended fixes, and the upgrade was successfully completed.

> DB::table("controlled_vocab_entry_settings")
>     ->whereIn("setting_name", [
>         "submissionAgency",
>         "submissionDiscipline",
>         "submissionKeyword",
>         "submissionLanguage",
>         "submissionSubject",
>         "interest"
>     ])
>     ->update(["setting_name" => "name"]);


```
H:\wamp64\www\ojs-3.5.0rc2>php tools/upgrade.php upgrade
2025-04-07 09:09:25 [pre-install]
2025-04-07 09:09:25 [load: upgrade.xml]
2025-04-07 09:09:25 [version: 3.5.0.0]
2025-04-07 09:09:25 [code: Installer Installer::checkPhpVersion]
2025-04-07 09:09:25 [code: Installer Installer::installDefaultNavigationMenus]
2025-04-07 09:09:26 [code: Installer Installer::migrateStaticPagesToNavigationMenuItems]
2025-04-07 09:09:26 [migration: APP\migration\upgrade\v3_4_0\I9813_QuickSubmitSubmissionProgressType]
2025-04-07 09:09:26 [migration: PKP\migration\upgrade\v3_5_0\PreflightCheckMigration]
2025-04-07 09:09:26 [migration: APP\migration\upgrade\v3_5_0\I8333_AddMissingForeignKeys]
2025-04-07 09:10:19 [Cleaning orphaned entries from "email_log" with an invalid value for the column "sender_id". The following IDs do not exist at the reference table "users" and will be reset to NULL: 13, 8, 26, 39, 68857, 68871, 68990, 68989, 68999, 68947, 69046, 69091, 69146, 69152, 69257, 69162, 69430, 68980, 69538, 69560, 69586, 69625, 69693, 69708, 69713, 69746, 69851, 69877, 69891, 69937, 69884, 69999, 70032, 70042, 70060, 70057, 69571, 70065, 70109, 70075, 70008, 70255, 70298, 70300, 70322, 69204, 70367, 70388, 70400, 70124, 70462, 70467, 70478, 70506, 70510, 70520, 70487, 70543, 70552, 70715, 70733, 68885, 70699, 70758, 70728, 70482, 70860, 70800, 70518, 70929, 70942, 70944, 70972, 70958, 71118, 71115, 71134, 71148, 71151, 71198, 71216, 71215, 69364, 70987]
2025-04-07 09:10:22 [168 entries updated]
2025-04-07 09:11:13 [migration: APP\migration\upgrade\v3_5_0\I9892_FloatToDecimalColumnTypeUpdate]
2025-04-07 09:11:13 [migration: PKP\migration\upgrade\v3_5_0\I9895_AddAppKeyToConfigFile]
2025-04-07 09:11:13 [migration: PKP\migration\upgrade\v3_5_0\I9678_RemoveScheduledTasksTable]
2025-04-07 09:11:13 [migration: PKP\migration\upgrade\v3_5_0\InstallEmailTemplates]
2025-04-07 09:11:13 [migration: PKP\migration\upgrade\v3_5_0\I9197_MigrateAccessKeys]
2025-04-07 09:11:49 [migration: PKP\migration\upgrade\v3_5_0\I9253_SiteAnnouncements]
2025-04-07 09:11:49 [migration: PKP\migration\upgrade\v3_5_0\I9262_Highlights]
2025-04-07 09:11:49 [migration: APP\migration\upgrade\v3_5_0\I9475_RecoverLayoutFiles]
2025-04-07 09:11:50 [migration: PKP\migration\upgrade\v3_5_0\I9462_UserUserGroupsStartEndDate]
2025-04-07 09:11:50 [migration: PKP\migration\upgrade\v3_5_0\I9552_UserGroupsMasthead]
2025-04-07 09:11:50 [migration: PKP\migration\upgrade\v3_5_0\I5504_UserGroupsSettings]
2025-04-07 09:11:50 [migration: APP\migration\upgrade\v3_5_0\I9425_SeparateUIAndSubmissionLocales]
2025-04-07 09:11:51 [migration: PKP\migration\upgrade\v3_5_0\I9709_UserUserGroupsMasthead]
2025-04-07 09:11:51 [migration: PKP\migration\upgrade\v3_5_0\I9566_UserRememberToken]
2025-04-07 09:11:51 [migration: PKP\migration\upgrade\v3_5_0\I9566_SessionUpgrade]
2025-04-07 09:11:51 [migration: PKP\migration\upgrade\v3_5_0\I9809_ReviewCancelDate]
2025-04-07 09:11:52 [migration: PKP\migration\upgrade\v3_5_0\I9860_EditorialMastheadNavMenuItem]
2025-04-07 09:11:53 [migration: APP\migration\upgrade\v3_5_0\I9937_EditorialTeamToEditorialHistory]
2025-04-07 09:11:53 [migration: PKP\migration\upgrade\v3_5_0\I10041_UserGroupsAndUserUserGroupsMastheadValues]
2025-04-07 09:13:05 [migration: PKP\migration\upgrade\v3_5_0\I9771_OrcidMigration]
2025-04-07 09:14:34 [migration: APP\migration\upgrade\v3_5_0\I10157_CreateAndMigrateIssueIdField]
2025-04-07 09:14:52 [migration: APP\migration\upgrade\v3_5_0\I5885_RenameReviewReminderSettingsName]
2025-04-07 09:14:52 [migration: PKP\migration\upgrade\v3_5_0\COA75_AddUserRoleEndEmail]
2025-04-07 09:14:52 [migration: PKP\migration\upgrade\v3_5_0\I10738_RemoveInvalidUserGroups]
2025-04-07 09:14:52 [migration: PKP\migration\upgrade\v3_5_0\I10362_EventLogEditorNames]
2025-04-07 09:15:37 [migration: PKP\migration\upgrade\v3_5_0\I10292_RemoveControlledVocabEntrySettingType]
2025-04-07 09:15:37 [migration: PKP\migration\upgrade\v3_5_0\I10292_UpdateControlledVocabAssocId]
2025-04-07 09:15:49 [migration: PKP\migration\upgrade\v3_5_0\I10292_UpdateControlledVocabEntrySettingName]
2025-04-07 09:16:21 [migration: PKP\migration\upgrade\v3_5_0\FilterClassNames]
2025-04-07 09:16:21 [migration: APP\migration\upgrade\v3_5_0\I10620_EditorialBoardMemberRole]
2025-04-07 09:16:21 [migration: APP\migration\upgrade\v3_5_0\I9707_WeblateUILocales]
2025-04-07 09:18:35 [migration: PKP\migration\upgrade\v3_5_0\I7135_CreateAuthorAffiliationsTables]
2025-04-07 09:18:35 [migration: PKP\migration\upgrade\v3_5_0\I7135_CreateNewRorRegistryCacheTables]
2025-04-07 09:34:43 [migration: PKP\migration\upgrade\v3_5_0\I10759_AddReviewAssignmentSettings]
2025-04-07 09:34:43 [migration: PKP\migration\upgrade\v3_5_0\I10819_OrcidOauthScopeMail]
2025-04-07 09:34:43 [migration: PKP\migration\upgrade\v3_5_0\I10359_DateConsideredToReviewAssignments]
2025-04-07 09:34:44 [migration: APP\migration\upgrade\v3_5_0\I4787_AddReviewSuggestionHelp]
2025-04-07 09:34:44 [migration: PKP\migration\upgrade\v3_5_0\I4787_InstallReviewerSuggestion]
2025-04-07 09:34:44 [migration: PKP\migration\upgrade\v3_4_0\I7624_StrftimeDeprecation]
2025-04-07 09:34:44 [note: docs/release-notes/README-3.5.0]
2025-04-07 09:34:44 [code: Installer Installer::addPluginVersions]
2025-04-07 09:34:44 [post-install]

Release Notes
----------------------------------------
OJS 3.5.0rc2 Release Notes
Git tag: 3_5_0rc2

Release date: March 20, 2025
============================

THIS IS A PRE-RELEASE VERSION OF THIS SOFTWARE AND IS NOT INTENDED FOR
PRODUCTION USE.

Configuration Changes
---------------------

See config.TEMPLATE.inc.php for a description and examples of all supported
configuration parameters.

New config.inc.php parameters added for general:
    - app_key (default value: ''), application specific key will used internally for encryption/decryption. This will be automatically added at upgrade.

New config.inc.php parameters added for security:
    - cipher (default value: ''), cipher algorithm used to generate app key and encryption purpose
    - cookie_encryption (default value: ''), allow cookie encryption when set

New config.inc.php section for schedule task named schedule is added, with the following parameters:
    - task_runner (default value: On), Whether or not to run the schedule tasks through web based task runner
    - task_runner_interval (default value: 60), How often should the built-in web based task runner run scheduled tasks in seconds
    - scheduled_tasks_report_error_only (default value: On), Whether or not schedule task execution failure details will be sent via mail

- The setting general.scheduled_tasks has been removed. It was supposed to control the schedule tasks but had no impact.

New config.inc.php parameters added for queues:
    - process_jobs_at_task_scheduler (default value: Off): Controls whether queued jobs should be executed together with the scheduled tasks.

New config.inc.php parameters added for caching:
    - default (default value: 'opcache'). Can be either 'file' or 'opcache' to indicate which Laravel caching implementation should be used.
    - path (default value: 'cache/opcache'). Use to specify a path for cache storage when using 'file' or 'opcache' drivers.


New Features
------------


Successfully upgraded to version 3.5.0.0

H:\wamp64\www\ojs-3.5.0rc2>
```

**Comment by shantanu198713** [comment]
Hi All,

We have successfully upgraded our system to OJS version 3.5.0rc2, and would like to report a few performance-related issues for your kind consideration:

- The Editorial section takes a considerable amount of time to load article lists.

- When switching simultaneously between multiple editorial tabs, the content often fails to load.

- On the Admin homepage, clicking on the Dashboard does not load the page or remains unresponsive.

To help illustrate these issues, please find a demonstration video here: [[Video Link](https://youtu.be/BhgylfPJ4bQ)]

 **Admin homepage, clicking on the Dashboard**

![Image](https://github.com/user-attachments/assets/a9d85926-695c-4dc5-97a1-f9f2ab781220)

**Comment by defstat** [comment]
@shantanu198713, thanks for reporting this. Could you please check if there are any JavaScript errors (in the browser's developer tools console) or PHP errors (in your server's error logs)? That information would help us in troubleshooting the issue.

**Comment by shantanu198713** [comment]
Hi @defstat 

No error was reported. However, the article list takes a significant amount of time to load — approximately one minute.

**Comment by asmecher** [comment]
@shantanu198713, regarding performance, I've just sent you a message via our support forum.

**Comment by asmecher** [comment]
Regarding [this issue](https://github.com/pkp/pkp-lib/issues/11194#issuecomment-2781974096) related to controlled vocabs, I've merged the PRs @touhidurabir wrote:
- https://github.com/pkp/pkp-lib/pull/11235
- https://github.com/pkp/pkp-lib/pull/11234

@shantanu198713, I'm going to close this as resolved; for other issues, let's create new entries to keep things organized. Thanks for reporting!

**Comment by shantanu198713** [comment]
Hi @asmecher 

We have successfully upgraded our system from OJS version 3.4.0-8 to 3.5.0.0 on our local environment. However, we are still experiencing slow loading ([previously reportred](https://github.com/pkp/pkp-lib/issues/11194#issuecomment-2782254911)) issues on the article listing pages, particularly when accessing submissions or managing articles in the editorial dashboard.

> We have successfully upgraded our system to OJS version 3.5.0rc2, and would like to report a few performance-related issues for your kind consideration:
> 
> * The Editorial section takes a considerable amount of time to load article lists.
> * When switching simultaneously between multiple editorial tabs, the content often fails to load.
> * On the Admin homepage, clicking on the Dashboard does not load the page or remains unresponsive.
> 
> To help illustrate these issues, please find a demonstration video here: [[Video Link](https://youtu.be/BhgylfPJ4bQ)]
> 
> **Admin homepage, clicking on the Dashboard**
> 
> ![Image](https://github.com/user-attachments/assets/a9d85926-695c-4dc5-97a1-f9f2ab781220)
