### ISSUE TITLE
[OMP] catalog cover image edit interface is confusing

### ISSUE THREAD

**Issue by crism** [pkp/pkp-lib#1157]
From #1127, against `HEAD`:

In a catalog entry, an item without a cover image shows a “broken image” in the browser for its current cover. The system should be aware there is no image, and display something appropriate, rather than making users wonder. Also, multiple users attempt to click on the broken image in order to replace it, rather than using the file upload affordance beside it.

An entry without a cover should have a placeholder. Without the broken image, the upload interface may be clearer (in terms of wanting to click on the image to change it), but it could still use a bit of work. I’m not sure what exactly would be better, but will keep thinking about it.

[While there, `s/it's/its/`…]

**Comment by asmecher** [comment]
@bozana, this touches on something you were recently working on; has it been fixed in the bargain?

**Comment by bozana** [comment]
@asmecher, hmmm... No I don't think this touches it and I think that this is already solved, right @crism?

**Comment by crism** [comment]
No, not solved; go to the catalog entry editing tab for a newly-created book, and you’ll see, under “Cover Image,” the browser’s broken-image icon with the alt-text “Current Image.” The file uploader tool shows right below that. (This is with `HEAD` as of late this morning CST.)

**Comment by bozana** [comment]
Hmmm... This is what I see -- is this the right place to look at?

![coverimage](https://cloud.githubusercontent.com/assets/378421/13335886/9a24287e-dc13-11e5-8197-16d52409a168.png)

**Comment by crism** [comment]
Hrm, no… Chrome on Windows shows it most clearly:
![broken_cover_chrome](https://cloud.githubusercontent.com/assets/1933900/13336249/b448effc-dbda-11e5-92a4-3aee5feaed42.png)
Firefox on Linux just shows the alt text:
![broken_cover_firefox](https://cloud.githubusercontent.com/assets/1933900/13336250/b44bc9d4-dbda-11e5-9136-f0dfce4afca9.png)
I just tried this with a completely brand new submission, so it’s not to do with the test submission having been created while an old bug existed.

**Comment by crism** [comment]
To add to that: on inspection, the code is:
```html
<div class="currentCoverImage">
	<img src="http://pww-dev.library.illinois.edu/omp_dev/index.php/pww_test/$$$call$$$/submission/cover/thumbnail?submissionId=5&amp;random=556cf7ec7f27d3" alt="Current Image" height="" width="">
	<span class="coverImageMessage description"></span>
</div>
```

**Comment by bozana** [comment]
@crism, do you have this file: templates/images/book-default-small.png? Can you access it with your BaseURL: ttp://pww-dev.library.illinois.edu/omp_dev/templates/images/book-default-small.png? This is the file that should be displayed...

**Comment by crism** [comment]
I have the file and can access it directly.

Oh! When I copy the image URL and open it in a new tab, I get a JSON message: “You have been denied access because you do not seem to be the author of this monograph.” Well, that explains it—while opening a couple of new questions.

**Comment by bozana** [comment]
Hm :-O Who are you? Hihihihi :-) You don't have to be the author... You don't have to have any role -- the reader should be able to see the image too... :-OOO

**Comment by crism** [comment]
I’m doing all this as the system administrator, journal manager, journal editor, and submitter… but in my experience, all users who can edit the catalog at all see this. Not sure why.

**Comment by bozana** [comment]
hm... can you see the image when the book is published, on the catalog or book page?

**Comment by bozana** [comment]
Aaaaa.... I see. This happens to me too, when the book is not in the production state...

**Comment by bozana** [comment]
Hmm... Only PublishedMonograph has the function getCoverImage. Thus, actually, this part (cover upload) shouldn't be there till the monograph is published or so... Actually audience part as well... Hmm...
@asmecher, any idea?

**Comment by bozana** [comment]
@asmecher, maybe to change the access policy for CoverHandler and move the get/setCoverImage to the Monograph class? -- So that the cover image can be handled at any time?

**Comment by crism** [comment]
I would definitely want to be able to set the cover image _before_ publishing the monograph. +1 to moving cover image accessors to `Monograph`.

**Comment by asmecher** [comment]
Yes, that sounds like a good idea.

**Comment by bozana** [comment]
@crism, could you please test the commit above? -- I think this solves the issue... :-)

**Comment by bozana** [comment]
Sorry @crism, I think now it should be fine -- could you please take a look at only this last commit?

**Comment by crism** [comment]
Sorry, @bozana—I wasted some time trying to test this against `HEAD`; didn’t realize you were on your own branch. I’ll play more with it tomorrow.

**Comment by bozana** [comment]
Oh, sorry for that @crism :-( THANKS!!!

**Comment by crism** [comment]
That seems to work, @bozana. Thanks!

**Comment by bozana** [comment]
Thanks a lot @crism! I made the PR https://github.com/pkp/omp/pull/243

**Comment by asmecher** [comment]
I've merged that PR -- closing this issue for now, though I'd love to hear your feedback, @crism.

**Comment by crism** [comment]
This seems to work for me. I confirmed it was broken against a very recent previous commit, then pulled this, and it looked fine.
