### ISSUE TITLE
[OJS] Issue galley grid retains `empty` class after a galley added

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1170]
If the grid in Edit Issue > Issue Galleys is empty, then you add a galley, the row is added but the `empty` class is still attached to the grid's `tbody`. As a result, the styling is off and the empty row indicator is visible.

**Comment by NateWr** [comment]
Ok, found a place where this can be replicated in OMP: when adding a reviewer to the reviewers grid for the first time.

**Comment by asmecher** [comment]
This should fix it.

**Comment by NateWr** [comment]
The discussions grid is still broken.

![pkp-discussions-empty](https://cloud.githubusercontent.com/assets/2306629/13568106/0c2c9c6c-e457-11e5-865e-5d7d32804718.png)

With most grids, the empty placeholder is a separate `tbody`. But in the discussions grid, the empty placeholder and the grid rows appear to be within the same `tbody`.

![pkp-discussions-empty-tbody](https://cloud.githubusercontent.com/assets/2306629/13568130/2dc18ca2-e457-11e5-9741-d90a1f62e23b.png)

As a result, `getEmptyElement` finds no `.empty` element at https://github.com/pkp/pkp-lib/blob/master/js/controllers/grid/GridHandler.js#L258. That means it can't be hidden at https://github.com/pkp/pkp-lib/blob/master/js/controllers/grid/GridHandler.js#L649.

**Comment by asmecher** [comment]
@beghelli, could you take a look at this? Best I can tell, the problem was introduced with grid features.

It seems to me that we need to create a `tbody` for the first row that's added to a grid, but currently the grid handler is adding the row to the `tbody.empty` placeholder. I'm a little lost in considering grid features, category grids, etc., which I suspect you're more conversant with.

With the fix I tried before reverted, you should see this on any grid -- I was using the reviewer grid (adding a reviewer to a blank list), and also the discussion grid on the same reviewer workflow page.

**Comment by beghelli** [comment]
Sure, taking a look at it.

**Comment by beghelli** [comment]
It has nothing to do with grid features. It happens when the grid handler in PHP returns a changed data event with the specific element id that has changed. If the grid is empty, then it will fetch only that specific row, and will try to find a tbody to add it. Since there is no other tbody for the grid to add the element, it gets the empty one.

I think that the solution is to always render the tbody that will hold the grid elements, even if it is empty. Will try that.

**Comment by beghelli** [comment]
found the problem: https://github.com/pkp/pkp-lib/commit/1b6e1acabff538643eb24ba79ea54fe4123b151b#diff-9284b2d34e4b30f44ea3c568d97ee8c3L78

Sorry @NateWr, I think I reviewed this but I didn't see this issue. Is there any specific reason you removed the empty tbody?

**Comment by beghelli** [comment]
I see now the problem, the extra tbody is making the x scroll bar visible if the grid has a scrollable div. I think the right way to handle this is to show only one tbody.

**Comment by asmecher** [comment]
Good stuff, @beghelli!
