### ISSUE TITLE
Review and update role permissions for Tasks & Discussions

### ISSUE THREAD

**Issue by blesildaramirez** [pkp/pkp-lib#11912]
**Description:**

There are a few access problems when managing tasks and discussions:
1. ~~Copyeditors can't view/add the tasks and discussions (returns a 401 error).~~ Fixed
2. ~~Assistant roles (e.g. copyeditor, layout editors) can't access the participants API, which is needed to load the participant options when creating a task or discussion.~~ Fixed by https://github.com/pkp/pkp-lib/issues/12009
3. ~~Authors cannot be assigned to a task/discussion. Currently returns an error: `Participant must be assigned to the submission in the current stage or be a reviewer.`~~ Fixed by https://github.com/pkp/pkp-lib/issues/11950
4. ~~Section editors who are only participants should not be able to edit or delete tasks/discussions.~~ Fixed
5. Owners of the task/discussion cannot view/edit/delete if they are not a participant.

Expected behavior:
1. Copyeditors should be able to view their assigned tasks and discussions and add new tasks/discussions.
2. Copyeditors/layout editors should have access to the participants API to create tasks/discussions.
3. Should be able to assign Authors to a task/discussion.
4. Section editors who are just participants should only be able to view task/discussions.
5. Owners of the task/discussion should be able to manage the task/discussion, even if they are not a participant.

**Steps to test the changes:**
For issue #1:
1. Login as a copyeditor.
2. View a submission on copyediting stage.
3. An error will appear `The current role does not have access to this operation.`.

For issue #2:
1. Login as a copyeditor/layout editor. 
2. View a submission, go to "Desk Review Tasks & Discussions" table.
3. Click Add
4. In the form, the participants options cannot be loaded because the API cannot be accessed by a user with an assistant role.

For issue #3:
1. Login as a journal manager. 
2. View a submission, go to "Desk Review Tasks & Discussions" table.
3. Click "Add"
4. Add a title, assign two participants (one being an author), add a discussion message.
5. Click "Submit".
6. The task/discussion is not saved, because of the error returned from the API.

For issue #4:
1. Login as a journal manager. 
2. View a submission, go to "Desk Review Tasks & Discussions" table.
3. Click "Add"
4. Add a title, assign two participants (one being a section editor), add a discussion message.
5. Click "Submit".
6. Login as the assigned section editor.
7. View a submission, go to "Desk Review Tasks & Discussions" table.
8. View the created discussion, click Edit.
9. Edit the title/discussion message.
10. Click "Submit".
11. Edit/Delete shouldn’t be allowed for participants of any roles except Journal Manager/Site Admin.

For issue #5:
1. Login as a non-journal manager role.
2. View a submission, go to "Desk Review Tasks & Discussions" table.
3. Click "Add"
4. Add a title, assign participants (excluding the current user), add a discussion message.
5. Tick "Enter task information", select a date and user responsible to complete it, select "Begin task upon saving"
6. Click "Submit".
7. An error will appear, because the owner cannot edit the task to "start" it after saving. Also, the table doesn't include the new task.

**What application are you using?**
OJS, OMP or OPS main

**Additional information**
Issue #1:
<img width="1903" height="987" alt="Image" src="https://github.com/user-attachments/assets/5a8e15dd-2f43-4835-9632-dc8d389b8d0c" />

Issue #2:
<img width="1906" height="847" alt="Image" src="https://github.com/user-attachments/assets/109b3c26-d86f-440b-9919-7a2fa2e7c2ae" />

Issue #3:
<img width="1903" height="831" alt="Image" src="https://github.com/user-attachments/assets/47002319-0a1d-4994-aeac-e3cc0447c282" />

Issue #4:
This also needs to be adjusted on the frontend.

Issue #5:
After saving the task with "Begin task upon saving" selected, the frontend will update the task to start it. This is the error shown:
<img width="1419" height="895" alt="Image" src="https://github.com/user-attachments/assets/6fd1a2ca-7cc3-4b0d-a5b3-7c3afc0ab751" />

**Comment by Tribunal33** [comment]
Thank you for making this a task @blesildaramirez .  Some of these permissions were established before.  Author is restricted from doing lots of things.  Copyeditor might have a setting to allow for others.  I think this might need a deeper look into what might be broken by reducing the restrictions on some of these areas.  

Number 1 looks similar to this : https://github.com/pkp/pkp-lib/issues/11320 except for copyeditors.  
Number 2 looks expected.  Author was not able to manipulate participants.
Number 3 Same thing Author not allowed these permissions.  This is expected.
Number 4 I would prefer blocking a user from doing something before they save but that seems to common practice.  Enabling/disabling functionality is the best choice.

**Comment by Vitaliy-1** [comment]
Think it's the same issue as: https://github.com/pkp/pkp-lib/issues/11950
The problem was that API incorrectly determined submission ID. Because of that permissions were calculated for the wrong submissions. I've merged the fix and I think all of these should be fixed.

**Comment by blesildaramirez** [comment]
Hi @Vitaliy-1 , the fix you mentioned above was for issue #3. I tested it, and it worked as expected.
However, the other issues mentioned in this ticket still persist. Could you please take a look? Thanks!

**Comment by Vitaliy-1** [comment]
Hmm, regarding the first issue - I don't do anything specific validations against copyeditors

**Comment by Tribunal33** [comment]
@Vitaliy-1 the problem isn't specific to copyeditors they are just `Assistants` role delegated to the copyediting stage.  Layout editor user roles who are also Assistants have issues with accessing the particpants list.  Similarly, the underlying problem with `Author` role is the permission level is not able to access the participants list.

Try this.  
1. Login with an author.
2. Find a submission and View it
3. Notice that the Participants list is now gone.

Reason: This section is hidden based on the permission level.

**Comment by Tribunal33** [comment]
Still ongoing testing but here are the tests so far.

1. Test Access to Tasks & Discussions from Author Role Assigned
2. Test Access to Tasks & Discussions from Author Role Not assigned
3. Test Access to Task & Discussions from Assistant Role with access to current stage
4. Test Access to Task & Discussions from Assistant Role without access to current stage
5. Test Task & Discussion is hidden for user not assigned as a participant
6. Test Editing Task & Discussion with Assitant permission (Layout editor)

**Comment by Vitaliy-1** [comment]
PR for fixes: https://github.com/pkp/pkp-lib/pull/12115
tests: https://github.com/pkp/ojs/pull/5224
@Hafsa-Naeem, I've made fixes for templates API and validation. Can you take a look?

**Comment by Hafsa-Naeem** [comment]
@Vitaliy-1  Thanks. I’ve reviewed the changes.. auth scoping and validation look aligned with our patterns, and the endpoints behave as expected in my checks. Looks great.

**Comment by Vitaliy-1** [comment]
For the issue number 4, modification of the write policy for the task and discussion:
PR https://github.com/pkp/pkp-lib/pull/12122
tests https://github.com/pkp/ojs/pull/5229

**Comment by Vitaliy-1** [comment]
PR for the issue number 5. The task or discussion creator should be a participant
PR: https://github.com/pkp/pkp-lib/pull/12255
tests: https://github.com/pkp/ojs/pull/5296

**Comment by Vitaliy-1** [comment]
@blesildaramirez, could you take a look if the fix works as expected?

**Comment by Vitaliy-1** [comment]
Ahh, forgot that creator can be null if task is automatically created. This means that when using form during editing we should count on that.

**Comment by Vitaliy-1** [comment]
I've updated that. Now it takes into account cases when task is automatically created. It will require testing when that functionality [is merged](https://github.com/pkp/pkp-lib/issues/11993#issuecomment-3805759169).

**Comment by Vitaliy-1** [comment]
PR to fix task list ordering: https://github.com/pkp/ui-library/pull/781
@blesildaramirez, can you take a look?

**Comment by blesildaramirez** [comment]
Hi @Vitaliy-1 , I approved this PR: https://github.com/pkp/ui-library/pull/781. For https://github.com/pkp/pkp-lib/pull/12255, this affected the cypress tests and it needs some fixing on the frontend. So I created this PR to resolve it: https://github.com/pkp/ui-library/pull/783

This [ojs test PR](https://github.com/pkp/ojs/pull/5110) is proof that both our fixes work in our cypress runs. 
We need to merge the frontend fixes first and then your pkp-lib PR so our tests will not break on main. 

Let me know if you have any questions. Thanks!

**Comment by mreiko** [comment]
@Vitaliy-1 cc: @Tribunal33 can this be closed?

**Comment by blesildaramirez** [comment]
Hi @mreiko , this can be closed as the latest issue has been resolved by https://github.com/pkp/pkp-lib/pull/12255.
