### ISSUE TITLE
Reviewer search is broken

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#12100]
### Valid Title

- [x] I have updated the title to accurately reflect the bug description

### Description

The reviewer search in OJS/OMP 3.5.0-2 is broken. See https://forum.pkp.sfu.ca/t/3-5-0-2-not-loading-search-in-add-reviewer/97520 for details.

This appears to be a regression caused by https://github.com/pkp/pkp-lib/issues/11791.

### Steps to Reproduce

1. Login with an Editor role
2. Navigate to a submission in review
3. Click the "Add reviewer" button
4. In the search box, type some text that will result in at least one patch
5. Check the error console and see a JS error.

### Expected Result

The search should present no errors and the expected reviewer matches.

### Actual Result

The search does not work and a JS error appears.

### Application Version

OJS 3.5.0-2

### Logs

TypeError: this.items.filter is not a function or its return value is not iterable
at Proxy.currentReviewers (build.js?v=3.5.0.2:3:130)
at vme (build.js?v=3.5.0.2:1:9181)
at get value (build.js?v=3.5.0.2:1:21188)
at Object.get [as currentReviewers] (build.js?v=3.5.0.2:1:52005)
at build.js?v=3.5.0.2:13:2493
at Nn (build.js?v=3.5.0.2:1:48284)
at Proxy.tct (build.js?v=3.5.0.2:13:1258)
at yB (build.js?v=3.5.0.2:1:74312)
at fw.Bt [as fn] (build.js?v=3.5.0.2:1:64722)
at fw.run (build.js?v=3.5.0.2:1:7744)
M8e @ build.js?v=3.5.0.2:1
n5 @ build.js?v=3.5.0.2:1
yB @ build.js?v=3.5.0.2:1
Bt @ build.js?v=3.5.0.2:1
run @ build.js?v=3.5.0.2:1
Ue @ build.js?v=3.5.0.2:1
Be @ build.js?v=3.5.0.2:1
M @ build.js?v=3.5.0.2:1
me @ build.js?v=3.5.0.2:1
ge @ build.js?v=3.5.0.2:1
ee @ build.js?v=3.5.0.2:1
M @ build.js?v=3.5.0.2:1
Bt @ build.js?v=3.5.0.2:1
run @ build.js?v=3.5.0.2:1
runIfDirty @ build.js?v=3.5.0.2:1
t5 @ build.js?v=3.5.0.2:1
Wme @ build.js?v=3.5.0.2:1
Promise.then
Ume @ build.js?v=3.5.0.2:1
aJ @ build.js?v=3.5.0.2:1
(anonymous) @ build.js?v=3.5.0.2:1
trigger @ build.js?v=3.5.0.2:1
KX @ build.js?v=3.5.0.2:1
_b @ build.js?v=3.5.0.2:1
set @ build.js?v=3.5.0.2:1
set @ build.js?v=3.5.0.2:13
t5 @ build.js?v=3.5.0.2:1
Rh @ build.js?v=3.5.0.2:1
dwe @ build.js?v=3.5.0.2:1
setItems @ build.js?v=3.5.0.2:13
success @ build.js?v=3.5.0.2:1
c @ jquery.min.js?v=3.5.0.2:2
fireWith @ jquery.min.js?v=3.5.0.2:2
l @ jquery.min.js?v=3.5.0.2:2
(anonymous) @ jquery.min.js?v=3.5.0.2:2
XMLHttpRequest.send
send @ jquery.min.js?v=3.5.0.2:2
ajax @ jquery.min.js?v=3.5.0.2:2
get @ build.js?v=3.5.0.2:1
(anonymous) @ build.js?v=3.5.0.2:1
Promise.then
Ta @ build.js?v=3.5.0.2:1
searchPhrase @ build.js?v=3.5.0.2:1
t5 @ build.js?v=3.5.0.2:1
Rh @ build.js?v=3.5.0.2:1
(anonymous) @ build.js?v=3.5.0.2:1
U @ build.js?v=3.5.0.2:1
t5 @ build.js?v=3.5.0.2:1
Wme @ build.js?v=3.5.0.2:1
Promise.then
Ume @ build.js?v=3.5.0.2:1
aJ @ build.js?v=3.5.0.2:1
(anonymous) @ build.js?v=3.5.0.2:1
(anonymous) @ build.js?v=3.5.0.2:1
trigger @ build.js?v=3.5.0.2:1
KX @ build.js?v=3.5.0.2:1
_b @ build.js?v=3.5.0.2:1
set @ build.js?v=3.5.0.2:1
set @ build.js?v=3.5.0.2:1
setSearchPhrase @ build.js?v=3.5.0.2:1
t5 @ build.js?v=3.5.0.2:1
Rh @ build.js?v=3.5.0.2:1
dwe @ build.js?v=3.5.0.2:1
(anonymous) @ build.js?v=3.5.0.2:1
b @ build.js?v=3.5.0.2:1
setTimeout
_ @ build.js?v=3.5.0.2:1
OGe.H.onKeyup.t..t. @ build.js?v=3.5.0.2:1
t5 @ build.js?v=3.5.0.2:1
Rh @ build.js?v=3.5.0.2:1
n @ build.js?v=3.5.0.2:1

**Comment by asmecher** [comment]
@Hafsa-Naeem, this appears to have been caused by a change in the way the `api/v1/users/reviewers` endpoint delivers results -- as a collection indexed by ID (which translates into a JSON object), rather than a list indexed sequentially (which translates into a JSON array).

At a glance, you can return to the expected behaviour with this change:
```diff
diff --git a/api/v1/users/PKPUserController.php b/api/v1/users/PKPUserController.php
index 900ac6dc3f..c88c84c4da 100644
--- a/api/v1/users/PKPUserController.php
+++ b/api/v1/users/PKPUserController.php
@@ -253,7 +253,7 @@ class PKPUserController extends PKPBaseController
 
         return response()->json([
             'itemsMax' => $collector->getCount(),
-            'items' => $items,
+            'items' => array_values($items),
         ], Response::HTTP_OK);
     }
```
...however, I'm not sure if other parts of the code need checking too.

**Comment by Rofypkr** [comment]
The file path is:
lib>pkp>api>v1>users>PKPUserController.php

Line no. 256

'items' => $items,
changed to
'items' => array_values($items),

Search is working now

**Comment by mjumbewu** [comment]
Thanks for the workaround!

FWIW, I can see that the same `'items' => $items,` is in the [return value for the `getMany` route](https://github.com/pkp/pkp-lib/blob/ee9ff04962ef7be592caf16dbbd78a926ccdf18b/api/v1/users/PKPUserController.php#L252-L257) in that file as well. That route is called from the main users & roles search, yet it seems to be working fine. The difference that I see is that in `getMany`, `$items` is defined as:

https://github.com/pkp/pkp-lib/blob/ee9ff04962ef7be592caf16dbbd78a926ccdf18b/api/v1/users/PKPUserController.php#L196

Whereas in `getManyReviewers` it's defined as:

https://github.com/pkp/pkp-lib/blob/ee9ff04962ef7be592caf16dbbd78a926ccdf18b/api/v1/users/PKPUserController.php#L252

(no `->values()`)

I don't know PHP well enough to know which change _should_ be made (i.e. add `->values()` to `$items` definition in `getManyReviewers`, or add `array_values` to the return in `getMany`?), but I made a best guess and opened a PR.

**Comment by Hafsa-Naeem** [comment]
@asmecher  Ready for review:

pkp-lib(stable-3_5_0): [pkp/pkplib#12100 fix(reviewers): array items for filtering #12112](https://github.com/pkp/pkp-lib/pull/12112)
ojs (stable-3_5_0): [pkp/pkp-lib#12100 Submodule update ##Hafsa-Naeem/i12100-stable-3_5_0-fix #5221](https://github.com/pkp/ojs/pull/5221)
ops (stable-3_5_0): [pkp/pkp-lib#12100 Submodule update ##Hafsa-Naeem/i12100-stable-3_5_0-fix #1157](https://github.com/pkp/ops/pull/1157)
omp (stable-3_5_0): [pkp/pkp-lib#12100 Submodule update ##Hafsa-Naeem/i12100-stable-3_5_0-fix #2189](https://github.com/pkp/omp/pull/2189)

**Comment by asmecher** [comment]
@Hafsa-Naeem, I checked the output of the affected API endpoints before https://github.com/pkp/pkp-lib/pull/11794 was committed against the results with https://github.com/pkp/pkp-lib/pull/12112 in place. There are still discrepancies:
- In the `api/v1/users/reviewers` endpoint, reviewer interests are broken. This was also reported [in the forum post](https://forum.pkp.sfu.ca/t/3-5-0-2-not-loading-search-in-add-reviewer/97520/6).
- In the `api/v1/user/123` endpoint (using a valid user ID in place of `123`), the new code causes the `reccomendOnly` flag on the user group to disappear.
There are possibly other discrepancies, I stopped there.

I'd suggest reviewing the API outputs for all affected endpoints previous to the first PR being applied, and making sure the new output matches.

ETA: Please see also [this comment](https://forum.pkp.sfu.ca/t/reviewer-list-when-assigning-reviewers/97165/4) about long lists for another scenario to test; not sure if it's a regression or pre-existing.

**Comment by Hafsa-Naeem** [comment]
@asmecher  Ready for review:

pkp-lib(stable-3_5_0): [pkp/pkplib#12100 fix(reviewers): array items for filtering #12112](https://github.com/pkp/pkp-lib/pull/12112)
ojs (stable-3_5_0): [pkp/pkp-lib#12100 Submodule update ##Hafsa-Naeem/i12100-stable-3_5_0-fix #5221](https://github.com/pkp/ojs/pull/5221)
ui-library(stable-3_5_0):  : [pkp/pkp-lib#12100 Fix reviewer API outputs, pagination #754
](https://github.com/pkp/ui-library/pull/754)

**Comment by jardakotesovec** [comment]
Sorry, I missed the follow-up on the pagination issue on forum. I updated my setting there.. hopefully should be getting notifications now.

I was now looking into why the pagination might have regressed there. And it turned out that its likely coming from the vue2 -> vue3 migration. There is mistake where fetch mixin is defining `itemsMax` as data and at the same time all these ListPanel component have `itemsMax` as prop. So they are pretty much fighting with each other and in vue3 the result is different and its not reading it from the props.

Solution is to remove the `itemsMax` from the fetch mixin and just rely on the `itemsMax` from props. Which btw fixes couple of other ListPanels, listed below.

Here is the PR for the ui-library: https://github.com/pkp/ui-library/pull/755 (**MERGED to 3.5 and main**)

Tested all components using fetch mixin:
- [x] HighlightsListPanel - missing pagination server side, but shows all highlights (tested with 100)
- [x] AnnouncementsListPanel - has pagination, tested
- [x] InstitutionsListPanel - has pagination, tested
- [x] SelectReviewerListPanel - has pagination, tested
- [x] AnnouncementsListPanel - has pagination, tested
- [x] CatalogListPanel - OMP - has pagination, tested
- [x] DoiListPane - has pagination, tested
- [x] PubMed Export Plugin, has pagination, tested
- [x] Native XML Plugin, has pagination, tested


Adding couple of screenshots from testing:

<img width="805" height="377" alt="Image" src="https://github.com/user-attachments/assets/a21f6337-3104-4fe9-8898-342d86e12e7a" />
<img width="873" height="281" alt="Image" src="https://github.com/user-attachments/assets/1a0246c6-2fc1-43b7-ba27-276e228240ff" />
<img width="1621" height="968" alt="Image" src="https://github.com/user-attachments/assets/953c4c79-ed0c-4df6-98d7-b1e2986471ca" />
<img width="1654" height="911" alt="Image" src="https://github.com/user-attachments/assets/7648c78d-9171-4811-8a1c-62882283c2eb" />

**Comment by asmecher** [comment]
@Hafsa-Naeem, the user interests still aren't working for me. With your changes in place I get:

<img width="1029" height="1079" alt="Image" src="https://github.com/user-attachments/assets/aaff99ed-2743-42b4-b844-11ba9b97fa1c" />
(Note the empty interests at the bottom.)

Before the first batch of changes, I used to get:

<img width="1032" height="1144" alt="Image" src="https://github.com/user-attachments/assets/be83841c-4ad2-47f8-8b83-7162e9cf42df" />

**Comment by jardakotesovec** [comment]
@Hafsa-Naeem @asmecher I merged ui-library fix to 3.5 and main, which was affecting couple of listing and basically preventing them from showing pagination. Affected&tested components are listed [above](https://github.com/pkp/pkp-lib/issues/12100#issuecomment-3637181118).

So you can focus on addressing the API issues.

**Comment by Hafsa-Naeem** [comment]
@asmecher  Ready for review.
pkp-lib(stable-3_5_0): [pkp/pkplib#12100 fix(reviewers): array items for filtering #12112](https://github.com/pkp/pkp-lib/pull/12112)
ojs (stable-3_5_0): [pkp/pkp-lib#12100 Submodule update ##Hafsa-Naeem/i12100-stable-3_5_0-fix #5221](https://github.com/pkp/ojs/pull/5221)
ui-library(stable-3_5_0):  : [pkp/pkp-lib#12100 Fix reviewer API outputs, pagination #754
](https://github.com/pkp/ui-library/pull/754)

**Comment by asmecher** [comment]
@Hafsa-Naeem, are you A/B testing your API request results? I'm still seeing [the same behaviour as above](https://github.com/pkp/pkp-lib/issues/12100#issuecomment-3639575632) with the latest commits.

**Comment by Hafsa-Naeem** [comment]
@asmecher  Yes, I compared the same API requests before and after the fix locally.
I verified both /users/{id} and /users/reviewers, and interests are now returned with the correct controlled vocab entry IDs.
If you're seeing different output, could you share the exact request (endpoint + params) so I can reproduce?

<img width="1391" height="675" alt="Image" src="https://github.com/user-attachments/assets/9b113808-2394-4e40-9000-87a4bd2495b5" />

**Comment by asmecher** [comment]
@Hafsa-Naeem, my steps to replicate the problem are:
1. Load the [test dataset for OJS `stable-3_5_0`](https://github.com/pkp/datasets/tree/main/ojs/stable-3_5_0)
2. Log in as `jjanssen`; go to the user profile > Roles tab; add two test reviewing interests; save the form
3. Log in as `dbarnes`; pick a submission in review; go to Add Reviewer
4. Enter `Julie` in the search box, and capture the request details for the resulting API query. The relevant parts are:
    ```
    http://.../index.php/publicknowledge/api/v1/users/reviewers?contextId=1&submissionId=12&reviewRoundId=9&reviewStage=3&searchPhrase=julie&count=30&offset=0
    ```
5. See that the reviewing interests I entered aren't present in the result.

Looking into it further, I see two problems:
1. In [`classes/user/Repository.php::preloadInterests`](https://github.com/pkp/pkp-lib/pull/12112/files#diff-9baf178242b77b99268385d1744ac5279323ae020cc045e75bf42e4c0ab8e240), you're using `interests` as the `setting_name` in `controlled_vocab_entry_settings`. Since [#10292](https://github.com/pkp/pkp-lib/issues/10292), it should be `name`.
2. User interests are stored in the `controlled_vocab_settings` table with `locale = ''`, but your changes take the current locale.

How did you get the user interests data you're testing with into your database?

**Comment by Hafsa-Naeem** [comment]
@asmecher Got it! This should work now. Ready for review
pkp-lib(stable-3_5_0): [pkp/pkplib#12100 fix(reviewers): array items for filtering #12112](https://github.com/pkp/pkp-lib/pull/12112)
ojs (stable-3_5_0): [pkp/pkp-lib#12100 Submodule update ##Hafsa-Naeem/i12100-stable-3_5_0-fix #5221](https://github.com/pkp/ojs/pull/5221)
ui-library(stable-3_5_0):  : [pkp/pkp-lib#12100 Fix reviewer API outputs, pagination #754
](https://github.com/pkp/ui-library/pull/754)

**Comment by Tribunal33** [comment]
Not sure if there are other locations to check, but I checked the following search bars and marked the ones that pass with an x.   
- [x] Front-office search
- [x] Submission search
- [x] Users & Roles
- [x] Reviewers
- [ ] Participants <-- This one has a slight anomaly that appears similar to previously broken search.  The only difference is that participants list search works slightly differently in that it doesn't try to search after every keystroke.  You must press enter to see the focus being lost.  Selecting the Search button (which isn't on other searches) works correctly.  

<img width="1598" height="784" alt="Image" src="https://github.com/user-attachments/assets/ca4e55a8-c9a1-4505-b20c-33f5c1127c8d" />

**Comment by jardakotesovec** [comment]
@Tribunal33 Listing (including search) in Assign participant is on legacy stack - so it might behave bit differently. I would suggest to consider it as out of the scope of this one. And I am on the fence whether bug ticket would be justified for that. It will get improved once we update that UI to vue.js.

**Comment by Tribunal33** [comment]
Thanks @jardakotesovec I will close it for now.  I don't see functionality broken for search so it is a minor annoyance that a very few users may even notice.

**Comment by Tribunal33** [comment]
Keeping open until merged to all branches.  
@Hafsa-Naeem or @asmecher please close when merged.

**Comment by asmecher** [comment]
Thanks, all, I've merged the pkp-lib PR to `stable-3_5_0` and forward-ported to `main`.
