### ISSUE TITLE
Fix/resolve LOCKSS registration/manifest/plugin

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#1908]
See http://forum.pkp.sfu.ca/t/archiving-via-lockss-and-clockss-problem/22963 for details.

@stranack, I think you also raised this somewhere, but I can't find it.

**Comment by asmecher** [comment]
@jmacgreg, this is assigned to you but I doubt you're going to have time for it in the next few weeks. Defer?

**Comment by bozana** [comment]
I could make these page function properly for this release and then maybe to take a deeper look and to improve it for the next. OK?

**Comment by bozana** [comment]
This is how the page looks like now, i.e. the metadata table:
![lockss1](https://user-images.githubusercontent.com/378421/31387498-fba0f80e-adca-11e7-9515-917740142bcf.png)

**Comment by bozana** [comment]
This is how the centered logos at the bottom of the page look like:
![locksslogos](https://user-images.githubusercontent.com/378421/31387916-7bc83ac8-adcc-11e7-9306-d9a80a02c7eb.png)

**Comment by bozana** [comment]
This is how the navigation at the top looks like:
![lockssnavigation](https://user-images.githubusercontent.com/378421/31388017-ec9fc4b4-adcc-11e7-96b4-dea73d0e9c53.png)

**Comment by bozana** [comment]
@jmacgreg already solved the issue, so fix is coming... :-)

**Comment by asmecher** [comment]
@jmacgreg, just a reminder that this is assigned to you for OJS 3.1 -- I think you already have a fix but need to open a PR, right? Let me know if I can help steward.

**Comment by asmecher** [comment]
Deferring to OJS/OMP 3.2.

**Comment by asmecher** [comment]
@jmacgreg, is this still something you want on your plate?

**Comment by mjordan** [comment]
@asmecher my apologies for #4274 and #4275. I did search the issue queue but somehow missed this.

**Comment by asmecher** [comment]
Not a problem, @mjordan, the issue queue is a labyrinth.

**Comment by jmacgreg** [comment]
Hi @asmecher, could you review the PR above? Quick note - these manifest pages are supposed to be non-localized, and I haven't touched the table code at all - this is just a modification to fix whether content is displayed at all (and to ensure that it's displayed in the front-end interface view, as opposed to the admin back-end). This page isn't supposed to be accessed by humans. Let me know if you have any questions.

**Comment by mjordan** [comment]
LOCKSS said they'd test if we want.

**Comment by asmecher** [comment]
(PR: https://github.com/pkp/ojs/pull/2215)

**Comment by mjordan** [comment]
Am I correct in understanding that users will need to upgrade to the upcoming dash release to get this fix, or can the updated plugin be delivered via the Gallery to users independent of the OJS version?

**Comment by jmacgreg** [comment]
Hi @mjordan, I'll see if I can get a test instance up today. Unfortunately, LOCKSS/CLOCKSS functionality isn't delivered via plugin - this is all core code, so the fix has to be applied to the codebase via github cherry-pick, patch, or system upgrade.

**Comment by mjordan** [comment]
@jmacgreg thanks for the clarification. Would you like me to coordinate testing with LOCKSS staff?

**Comment by rshiggin** [comment]
A quick comment from IUSCholarWorks' journal program at IU Bloomington (https://scholarworks.iu.edu/journals on 3.1.1.4). The .diff file works by running a standard patch command: `patch -p1 < patch_file.diff`
We'll be in touch ourselves with the technical team (namely, Alexandra Ohlson) at CLOCKSS to verify the revised manifest we now see.

**Comment by mjordan** [comment]
@rshiggin Alexandra is who I am talking to. If you are already in contact with her for testing, that's great.

**Comment by jmacgreg** [comment]
HI @rshiggin, sounds great! I'll leave it in your hands for testing w/LOCKSS unless I hear otherwise. Let me know here if any other changes are requested.

**Comment by mjordan** [comment]
@rshiggin I've pinged Alexandra to say you and she can perform initial testing, but to echo @jmacgreg, let us know if you need anything from the PKP team.

**Comment by rshiggin** [comment]
Thank you. I'll report back here.

**Comment by rshiggin** [comment]
Hello @mjordan and @jmacgreg,

Apologies for the delay. We've run this patch on our production multi-site instance. e.g., https://scholarworks.iu.edu/journals/index.php/sdh/gateway/clockss. Alexandra Ohlson with CLOCKSS support has verified that it works (clockss-publishertechnical@support.clockss.org). Although she did have a couple of questions about what is default language and what is not in OJS 3. 

However, we are experiencing a bug with journals in our system that don't have LOCKSS or CLOCKSS enabled. We don't know whether this is related to the patch or not. The save preference function for the tab in website settings (settings::website::archiving) is returning an error. Although it does work for the other tabs in Website Settings.  We have the following error messages:

**error log**
```
PHP Warning:  Missing argument 1 for ContextSettingsForm::execute(), called in /srv/services/journals-prod-webapp-8120/htdocs/journals/lib/pkp/controllers/tab/settings/archiving/form/ArchivingForm.inc.php on line 91 and defined in /srv/services/journals-prod-webapp-8120/htdocs/journals/lib/pkp/classes/controllers/tab/settings/form/ContextSettingsForm.inc.php on line 123
PHP Notice:  Undefined variable: request in /srv/services/journals-prod-webapp-8120/htdocs/journals/lib/pkp/classes/controllers/tab/settings/form/ContextSettingsForm.inc.php on line 124
PHP Notice:  Undefined variable: request in /srv/services/journals-prod-webapp-8120/htdocs/journals/lib/pkp/classes/controllers/tab/settings/form/ContextSettingsForm.inc.php on line 125
```
**browser console**   
```
Form method
Request URL: https://scholarworks.iu.edu/journals-playground/index.php/inula/$$$call$$$/tab/settings/website-settings-tab/save-form-data?tab=archiving
Request Method: POST
Status Code: 500 Internal Server Error
Remote Address: 156.56.241.15:443
Referrer Policy: no-referrer-when-downgrade
```     
Thanks!

**Comment by rshiggin** [comment]
I'm attaching the .diff file (as .txt) that we used, in case it's a different version. Thanks again!
[clockss-lockss.txt](https://github.com/pkp/pkp-lib/files/2696426/clockss-lockss.txt)

**Comment by jmacgreg** [comment]
Hi @rshiggin, thanks for the feedback! I can't seem to replicate this. Are you seeing the error when you try and save the Archiving ettings page, or elsewhere? Do you get any "Your changes have been saved" notification at all? (This isn't one of OJS' normal upper-right pop-ups for some reason, it's embedded in the page once you hit save.)

**Comment by rshiggin** [comment]
Apologies for the delay in responding. We are experiencing the problem after applying the patch. The error occurs only for the "Archiving" tab. We see a spinning circle to the right of the save button rather than a notification. The other tags do respond on save with a green-background, pop-up notification in the upper right corner. 

Above, in my original reply, I posted the relevant lines from our PHP log.

**Comment by rshiggin** [comment]
Alexandra Ohlson at CLOCKSS has also asked me if she can recommend this patch to other orgs and users of OJS. We know that the patch works well enough to give CLOCKSS the right manifest to restart the preservation of OJS 3 content. But I'm concerned that it has given us the bug in selecting an archiving method. 

**Can we get the patch tested and released so that CLOCKSS can recommend it to other users?**

Many thanks,
Richard Higgins
Indiana University Libraries

**Comment by rshiggin** [comment]
Thank you for looking at this @jmacgreg . Here's the PHP set of errors produced when we try to save an Archiving setting to CLOCKSS.

```
[Wed Jan 16 20:36:04.341788 2019] [:error] [pid 9370] [client 156.56.241.82:43766] PHP Warning:  Missing argument 1 for ContextSettingsForm::execute(), called in /journals/lib/pkp/controllers/tab/settings/archiving/form/ArchivingForm.inc.php on line 91 and defined in /journals/lib/pkp/classes/controllers/tab/settings/form/ContextSettingsForm.inc.php on line 123, referer: https://scholarworks.iu.edu/journals/index.php/IJES/management/settings/website
[Wed Jan 16 20:36:04.341819 2019] [:error] [pid 9370] [client 156.56.241.82:43766] PHP Notice:  Undefined variable: request in /journals/lib/pkp/classes/controllers/tab/settings/form/ContextSettingsForm.inc.php on line 124, referer: https://scholarworks.iu.edu/journals/index.php/IJES/management/settings/website
[Wed Jan 16 20:36:04.341830 2019] [:error] [pid 9370] [client 156.56.241.82:43766] PHP Notice:  Undefined variable: request in /journals/lib/pkp/classes/controllers/tab/settings/form/ContextSettingsForm.inc.php on line 125, referer: https://scholarworks.iu.edu/journals/index.php/IJES/management/settings/website
[Wed Jan 16 20:36:04.341833 2019] [:error] [pid 9370] [client 156.56.241.82:43766] PHP Fatal error:  Call to a member function getContext() on null in /journals/lib/pkp/classes/controllers/tab/settings/form/ContextSettingsForm.inc.php on line 125, referer: https://scholarworks.iu.edu/journals/index.php/IJES/management/settings/website
```

**Comment by rshiggin** [comment]
Also, is your commit today (22f1d22) revised from version of the patch we ran Dec. 12? 

I'll let Alexandra at CLOCKSS know that it will be in release 3.1.2. Having the preservation process working again is a big deal for us. A huge thanks for pushing this through.

**Comment by asmecher** [comment]
Fixed and forward-ported, @jmacgreg!

**Comment by jmacgreg** [comment]
Thanks @asmecher! 

@rshiggin, I unfortunately still can't replicate this. It may be that something in the 3.1.1 branch has been updated - I'm running the most recent version here - or it could be the PN plugin or another plugin interfering with stuff. I'm going to keep this closed for now, but if you encounter the same problem post-3.1.2, please reopen or open a new issue. 

And yes - the commit last night is a revised version, but only very slightly - removing some dead code. It should be the patch to use going forward, though.
