### ISSUE TITLE
[OJS] Localised filenames complicate uploading submission files in multilingual journals

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#2114]
The issue is described here: http://forum.pkp.sfu.ca/t/ojs3-uploading-submission-files-in-multilingual-installations-does-the-file-name-have-to-be-localized/26842/1

The easiest solution would be to use only the primary locale for filenames.

**Comment by NateWr** [comment]
Just copying the report here for ease.

> I noticed a problem when uploading submission files to multilingual journals.
>
> After uploading a file you get to step 2 where you see the name the system has given to the file.
>
> In this case the Finnish locale is selected (I will pr the whole locale soon) and you see the file name as expected.
>
> However the Continue button (Jatka) is disabled, so you are basically stuck. For a long time I thought that the system has crashed but a couple of days ago I realized that this happens, if an user is submitting a manuscript and is using some other locale than the primary locale in the UI.
>
> Basically the user should realize here that they should push the edit button and enter a file name to the > English (primary) locale field as well
> 
> This is of course way too difficult and complicated.
> 
> My question:
> 
> Why should the filename be localised at all?
> And if it should be localised, could it be prefilled to all available locales using the same name so that users do not get stuck this way.

**Comment by asmecher** [comment]
No strong feeling on whether this should be localized or not -- but in case it helps: this isn't really a "filename" in the normal sense. There are two of those that we track, the filename per the uploading system and the one that OJS assigns for server-side storage, and neither of course is localized. The name field that you're referring to is metadata, and could conceivably be useful localized.

There are other cases where this might arise in other fields, e.g. when uploading a supplementary file, which IIRC has different required fields. Maybe we're missing a UI cue for missing data, or maybe a different default language should be presented instead for that field?

**Comment by ajnyga** [comment]
Thanks,

I realize this is not a actual filename, I just used it in lack of a better word. 

A visual cue would of course help to spot the problem. However, it would still be very unclear for the average author to determine what kind of name should they write there. 

Also, if the script would show the primary locale name instead of the locale the author is using, the author would then probably only see a blank space and the pen icon? And the author would still have to figure out what kind of name is expected here.

Could the upload script just fill in all the language versions automatically? Like it does with the locale the author is using?

**Comment by NateWr** [comment]
> Could the upload script just fill in all the language versions automatically? Like it does with the locale the author is using?

If we want this to be localized, this would be the route I'd go. It falls into the bucket of asking someone to localize something in a language they may not know, so better to just auto-fill it and leave it alone. 

We already discourage people editing it anyway by hiding the input field until the user clicks the edit link.

**Comment by asmecher** [comment]
It shouldn't be necessary to fill in *all* values -- just the right one. But agreed, we should pre-fill the required locale, even if that introduces a potential language mismatch (consider primary locale != submission locale).

**Comment by ajnyga** [comment]
Hi, thanks.

If only the filename for the primary locale would be auto-filled, what locale would show for the author using another locale? I mean, would there be a blank field in step 2 with only the pen icon visible?

Two other things with filenaming. I know that these are separate issues but still connected:

1. The filename now includes the file format. If that changes in a revision, the original file format is still visible. Of course you can change that manually, but it will probably raise questions among the authors. 

2. It is also a bit problematic that if an author has submitted an article called "my-article.docx" it is visible as "Author, my-article.docx" in OJS3. Now when the author comes back to upload a revision of that article and has renamed the file on her computer as "my-revised-article.docx", the system is still showing the original filename (Author, my-article.docx) after the upload. Of course it is a new revision, but will probably be confusing for the authors who may think that they have not succeeded in uploading the new version at all.

**Comment by asmecher** [comment]
The way OJS treats multiple languages is as follows: there's always a "primary" locale (generally the journal's primary locale), and required fields are always required in that language. For all other languages the translation is purely optional. When a piece of data isn't available in the user's current language, the system falls back on the primary locale.

**Comment by ajnyga** [comment]
I realize this. I think that any solution here is good as long as the "Continue" button is not disabled in step 2 by default for the submitting author when adding a new file.

**Comment by ajnyga** [comment]
@asmecher, @NateWr I have started to get feedback on this issue. Most authors are clueless on how to get past the step 2 in file upload form. The reason is described in the forum post with screencaptures.

I would be happy to try and solve this, but what is the preferred solution here?

In my opinion, the filename should be automatically filled with all active form locales.

**Comment by asmecher** [comment]
@ajnyga, here's what I'd suggest:

- Ensure that the required fields are required in the *submission*'s locale (as opposed to the journal's locale).
- Have the default name fill in the submission's locale field to meet that requirement.

Does that make sense?

**Comment by ajnyga** [comment]
@asmecher I can not come up with any scenarios where that would not work.

Or is there a problem, if the users UI locale is not the same as the submission locale? French speaking author submitting a manuscript written in English using the French UI.

**Comment by asmecher** [comment]
The system will first try to find metadata in the user's UI locale, then fall back on the submission's locale, for which the required metadata should always be available.

**Comment by ajnyga** [comment]
I first thought that what needs to be defined is `requiredLocale` in `SubmissionFilesMetadataForm`: https://github.com/pkp/pkp-lib/blob/master/classes/form/Form.inc.php#L89. However, that does not seem to affect anything, because `getRequiredLocale` function is not used anywhere in OJS or pkp-lib.  (Should it be used here? https://github.com/pkp/pkp-lib/blob/master/classes/form/Form.inc.php#L342)

So, whatever locale is the first input field in a form is also required together with the primary locale. And the locale that is first, is set here with the assigning of `formLocale`: https://github.com/pkp/pkp-lib/blob/master/classes/form/Form.inc.php#L190 & https://github.com/pkp/pkp-lib/blob/master/classes/form/Form.inc.php#L350

So basically setting that `formLocale` value to match $article->getLocale() would solve the problem and the forms would show the submission locale first, I think?
Not to mess up too much with the current `Form.inc.php`, I would suggest that we introduce a new locale value `submissionLocale` which can be set from for example` SubmissionFilesMetadataForm __construct` and `PKPSubmissionSubmitStep3Form` and will be checked inside `Form::getFormLocale` as the first alternative. Basically you could override the locale settings with that value from any form where you want to use some other locale instead of the user locale as the first alternative. The primary locale would still be needed as well. (a minor issue here is that the tinymce fields only seem to validate against the primary locale in any case, but this is clearly a separate issue).

This would be fix number 1 and would follow the logic of your first point. 

However, that does not solve the original problem with the file name and the inactive button, because the file name is still set to match only the `primary locale` here: https://github.com/pkp/pkp-lib/blob/master/classes/submission/SubmissionFileDAODelegate.inc.php#L99

My suggestion is that the file name should be set two times there, first with primary locale and the second one with the submission locale which after fix number 1 is the other needed locale

This would be fix number 2

Any comments @asmecher ? I have these changes basically ready for a pull request it this sounds good enough?

**Comment by ajnyga** [comment]
Just to add that we could also fix only the original issue by doing a second setName here  https://github.com/pkp/pkp-lib/blob/master/classes/submission/SubmissionFileDAODelegate.inc.php#L99 using the value from `getUserVar('formLocale')`.

**Comment by ajnyga** [comment]
The above suggestion https://github.com/pkp/pkp-lib/issues/2114#issuecomment-280702916 as a pull request: https://github.com/pkp/pkp-lib/pull/2303

The only problem here is that the tinymce field is required only for the primary locale while the other fields are required for two locales.

Also, I do not know whether the "overrideLocale" approach is the one you want to use here @asmecher ?

**Comment by bozana** [comment]
Hmmm... I have a few comments/questions:
1) 
Are we sure we want the submission locale to be required and thus automatically filled for file names? -- The other possibility would be to just require the UI locale, without automatically filling anything else. Those file names are just for the work within the system, in the workflow -- not provided publicly, right?
This function is used everywhere in the workflow, not only in the submission, so lets see the examples for both cases:
a) submission locale required and automatically filled:
If an user is using ES UI language but the submission is in DE, the automatically filled name would actually be in Spanish (but saved as DE). 
b) require only UI locale name:
If the submission is in DE and the author entered the DE name, an editor using EN UI, who is wishing to change the file name, would have to insert the EN name too. Else, here, when uploading a new file, just the name in the current UI locale would have to be entered and nothing automatically filled.

2)
The other thing I would change is, that I would not require the journal primary locale, neither for the file names, nor for the submission metadata, as it is in your current solution @ajnyga. OK?
 
3)
For the submission metadata I would define the default form locale = submission locale and only require that locale. OK?

Here the possible solution for the 1b, 2 and 3:  https://github.com/bozana/pkp-lib/commit/90e9b510609c9ec820298fb7547c7d0cc19ef4e1

@asmecher, @ajnyga, what do you think?

**Comment by ajnyga** [comment]
Thanks @bozana 

Regarding points 2 and 3:
That is true that in my pr the primary locale is required as well, or actually the current OJS3 code requires the primary locale to be filled always (basically in all forms). 

For me it seems logical that only one locale is required and it is always the submission locale! It was actually hard to find a working solution with two required locales so this definitely clears things to the right direction.

Regarding point 1, I am maybe not understanding you correctly when you write about UI locale. I mean, why not just use the exact same logic here as in 2 and 3: automatically fill the file name with the submission locale and only require that locale?

I mean if we want to localise the file name field, then it would make sense that the required locale (which is also filled automatically) is the same as the one that is required for the article metadata. And the locale that is required for the article metadata should be, like you and @asmecher suggested, the same as the submission locale. And the submission locale could be in many cases different than the UI locale. 

Or am I missing something here (point 1a/b)?

I did not see any changes to classes/submission/SubmissionFileDAODelegate.inc.php where the file name is set with $submissionFile->setName($submissionFile->_generateName(), AppLocale::getPrimaryLocale()). Or is it trivial what the actual name is as long as it is set? (which brings me to https://github.com/pkp/pkp-lib/issues/2235 ;)

**Comment by bozana** [comment]
Hi @ajnyga 

I was thinking that the file names are slightly different than submission metadata: The submission metadata belong to the published submission and they will be exported and used elsewhere. Thus they have to be coherent and have all metadata in at least the submission language. The files are however used differently, I believe, and their name is only a metadata used internally between the different users in the workflow, right? And those users use different languages: an author can submit in DE, the editor can use FI and communicate with reviewers in FI, etc. Thus, when the editor using FI would upload a file for reviewers, the file name would be actually in Finish, but it would automatically be copied for DE as well (and currently even for the primary journal locale). It is not so bad, but I am not sure if necessary?

Thus, yes, for majority of forms it is necessary that the journal primary locale is there and it makes perfectly sense. But for submission metadata it is definitely not the case. And for the file names not necessarily, I believe?

You are right, the appropriate changes in classes/submission/SubmissionFileDAODelegate.inc.php are missing, the AppLocale::getPrimaryLocale() would be changed to AppLocale::getLocale() for 1b). The change is coming to the commit above...
But I could also only consider the submission locale there if wished so...

**Comment by bozana** [comment]
Hmmm... Now I see, that the solution not to consider the journal primary locale for file names leads for file names being displayed like "1-1-1-PB.pdf" if the name is missing in the current UI locale...

**Comment by bozana** [comment]
OK, we could probably solve the file name display with the implementation of the getLocalizedData function for SubmissionFile.inc.php (e.g. to display the first found name)...
So the question is:
-- should the file names be required in the submission locale or UI locale, and
-- should the file name be always provided/copied for the journal primary locale (this would make the display slightly easier)

**Comment by ajnyga** [comment]
Regarding https://github.com/pkp/pkp-lib/issues/2114#issuecomment-283077752
I see your point and that is exactly why I originally suggested that the file name should not be localised at all. I mean different language versions of the same file name could even confuse people.

So maybe:
- do not localise the file name (and reconsider the way it is created: no original file name or file type visible)
- use submission locale for as the only required locale for submission metadata and also for supplementary file metadata (I mean article components with more metadata than just the file name)
- use primary locale as the only required locale for all the rest of the forms in OJS

**Comment by bozana** [comment]
Yes, maybe... 
I would like to find the solution to solve the problem here first, with the concept as it is now, then we could maybe consider making the file names not localized, because this means even more changes...
I'll try to test, how it would be if we would only use submission locale, without the copy for the journal primary locale...

**Comment by ajnyga** [comment]
As I mentioned above, regarding the problem with the file name  I am happy with any solution that prevents the problem I originally described from happening.

Regarding the use of submission locale as the only required locale for the submission metadata, this is definitely a good idea as well, but somewhat separate from the actual issue here.

**Comment by bozana** [comment]
Well, I think now I encountered another problem: if I want a key to be translated in other locale than UI, it does not work -- it seems that registry does not contain other locales, only the current UI locale... :-P

**Comment by bozana** [comment]
:-P Yes, I forgot `AppLocale::requireComponents(LOCALE_COMPONENT_PKP_COMMON, $submissionLocale);`

**Comment by bozana** [comment]
OK, I tested it, and it should work that we require only submission locale, and not also journal primary locale. Also, when getLocalizedData is used for submission files, the submission locale is first considered, if the UI locale is not there.
In the function _generateName, the keys are translated into the submission locale, to have the proposed file name in the submission locale.
Does all this make sense?
I will commit this changes, so you could see and decide...

**Comment by bozana** [comment]
Here the current changes: https://github.com/bozana/pkp-lib/commit/a64cfad959d5bdc5ff988c2ac6029c38820b9087

**Comment by ajnyga** [comment]
Thank your, I will take a better look tomorrow, but was just wondering whether the old submissions are somehow affected by these changes. I mean whether there will be problems with all the submissions have used the old logic for the locales?

**Comment by bozana** [comment]
@ajnyga, I don't think so -- if the file name in UI and submission locale is not found, any other found name will be displayed. Only if a user edits the form and there is no entry for submission locales, he/she will have to enter it.

**Comment by bozana** [comment]
@asmecher, could you maybe also take a look (s. https://github.com/bozana/pkp-lib/commit/a64cfad959d5bdc5ff988c2ac6029c38820b9087) and especially:
-- if it is OK to only require submission locale input for files and submission metadata, and no journal primary locale at all
-- how the file names are generated (using the submission locale for translation)

**Comment by asmecher** [comment]
@bozana, looks good -- but I do think the getLocalizedData function's performance hit needs attention before merging.
@ajnyga, does this approach look like it'll resolve things for you?

**Comment by ajnyga** [comment]
Very much so, more than originally suggested. I mean I did not think that much about the rest of the metadata, but now that the topic has been discussed using only the submission locale as the required one makes a lot sense. Regarding the original topic, I am happy with any solution that does not confuse authors. I did not have the time to test the code yet, but will tomorrow. Thanks!

**Comment by asmecher** [comment]
We're within a hair of having this done -- but I'm going to push it over to OJS 3.1 so I can get OMP 3.1 released. (We don't have any reports of this showing up amongst our current OMP users, so I suppose none of them have the required language config to cause it.) I don't mind if it gets merged the day after the OMP 3.1 release :)

**Comment by bozana** [comment]
PR:
lib-pkp master: https://github.com/pkp/pkp-lib/pull/2332
ojs master: https://github.com/pkp/ojs/pull/1287 (only submodule update)

**Comment by bozana** [comment]
@asmecher, could you take a look at the PR?

**Comment by asmecher** [comment]
Looks good, @bozana, please go ahead. I don't love the way we're moving `submissionLocale` into `SubmissionFile`, but I think it's OK for now; if we find we need a better pattern or need to use this one repeatedly, we can clean it up later. Thanks!

**Comment by bozana** [comment]
Thanks @asmecher! I added the comment for the get/setSubmissionLocale and merged. This should be cherry-picked to ojs-stable-3_0_2, right?

**Comment by asmecher** [comment]
Yes, I think so, thanks!

**Comment by bozana** [comment]
Everything merged, thus closing...

**Comment by defstat** [comment]
@asmecher @bozana @ajnyga 

Here 
https://github.com/defstat/quickSubmit/tree/pkp/pkp-lib%232114-QuickSubmitPlugin-submission-language-fix

are some changes regarding the functionality described above, for the QuickSubmitPlugin. 

I am not sure if it is already done, but shouldn't we change other core forms like 
https://github.com/defstat/pkp-lib/blob/master/controllers/grid/users/author/form/AuthorForm.inc.php#L31
or 
https://github.com/pkp/ojs/blob/master/controllers/grid/articleGalleys/form/ArticleGalleyForm.inc.php#L31

to incorporate the change, by adding `$this->setDefaultFormLocale($submission->getLocale());` to their constructors?

**Comment by defstat** [comment]
QuickSubmitPlugin PR: pkp/quickSubmit#7

**Comment by bozana** [comment]
@defstat, merged...
I think that we could set the submission locale for AuthorForm as well, and the submission locale could be selected per default in the ArticleGalleyForm, but not required (because also other languages are possible). Also, the file metadata form should have the article galley language as default (and not the UI language as it is now).

**Comment by bozana** [comment]
> I think that we could set the submission locale for AuthorForm as well, and the submission locale could be selected per default in the ArticleGalleyForm, but not required (because also other languages are possible). Also, the file metadata form should have the article galley language as default (and not the UI language as it is now).

@ajnyga, would you agree with this? You have a real scenario i.e. multi-lingual and multi journal installation :-)

**Comment by ajnyga** [comment]
Hi @bozana and @defstat, this sounds logical to me, especially the galleyForm! Next step is to implement multilingual author names ;)

And FYI, it is snowing in Helsinki. Snowing. In mid-May.

**Comment by bozana** [comment]
Wow, and I thought Berlin weather is not good :-) Although, I remember one year it was snowing in May here too :-)

**Comment by ajnyga** [comment]
Hi @defstat and @bozana 
After applying https://github.com/pkp/pkp-lib/pull/2333 I am getting this error when trying to upload a new galley file:
`[Tue May 09 15:18:43 2017] [error] [client 192.xxx] ojs2: Unknown locale component , referer: http://site.fi/journal/management/importexport/plugin/QuickSubmitPlugin`

Applying https://github.com/pkp/quickSubmit/pull/7 does not fix it.

**Comment by bozana** [comment]
@ajnyga, could you please also test if this fix solves it -- it does for me: https://github.com/pkp/quickSubmit/pull/9

**Comment by ajnyga** [comment]
hi @bozana, yes it works now, thank you!

I do get  `PHP Fatal error:  Call to undefined method PublishedArticleDAO::getByArticleId() in plugins/importexport/quickSubmit/QuickSubmitForm.inc.php on line 74`, it is easily fixed by changing that to getById, but not sure what that is about? We have OJS3.0.2, the original February flavor.

**Comment by ajnyga** [comment]
I am also getting these now:

```
[Wed May 10 22:57:48 2017] [error] [client 10.8.0.6] PHP Notice:  Undefined index: published_submission_id in classes/article/PublishedArticleDAO.inc.php on line 544, referer: https://site.fi/journal/management/importexport/plugin/QuickSubmitPlugin

[Wed May 10 22:57:48 2017] [error] [client 10.8.0.6] PHP Notice:  Undefined index: issue_id in classes/article/PublishedArticleDAO.inc.php on line 545, referer: https://site.fi/journal/management/importexport/plugin/QuickSubmitPlugin

[Wed May 10 22:57:48 2017] [error] [client 10.8.0.6] PHP Notice:  Undefined index: seq in classes/article/PublishedArticleDAO.inc.php on line 546, referer: https://site.fi/journal/management/importexport/plugin/QuickSubmitPlugin

[Wed May 10 22:57:48 2017] [error] [client 10.8.0.6] PHP Notice:  Undefined index: access_status in classes/article/PublishedArticleDAO.inc.php on line 547, referer: https://site.fi/journal/management/importexport/plugin/QuickSubmitPlugin
```

**Comment by bozana** [comment]
Phew... Thanks a lot @ajnyga, I will investigate... :-)

**Comment by bozana** [comment]
@ajnyga, in the same PR I now removed these two lines from the constructor:

> $publishedSubmissionDao = DAORegistry::getDAO('PublishedArticleDAO');
> $this->publishedSubmission = $publishedSubmissionDao->getByArticleId($this->submissionId, $this->context->getId(), false);

That should solve the problem, I think -- at that point there is no such published article, leading to those messages -- the `publishedSubmission` is only needed in the function `execute`.

**Comment by ajnyga** [comment]
ah of course, thanks!

**Comment by ajnyga** [comment]
Hi,

Just got informed that this problem is back in 3.1.0.1. 

I will write the details to another topic.
