### ISSUE TITLE
[OJS] Variable names visible in Editorial history

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#2160]
Some of the variables do not get a value in editorial history in OjS 3.0.1.

For example:
Revision "{$name}" (file ID 61821-{$revision}) was uploaded (added in OJS3)
Anon has been assigned to review submission {$submissionId} for review round 1. (migrated from OJS2) 
Anon has declined the round 1 review for submission {$submissionId} on behalf of Anon. (migrated from OJS2)
 ##submission.event.participantRemoved##

**Comment by asmecher** [comment]
- Shared `submission.event.participantRemoved` and `submission.event.participantAdded` in PKP lib (wasn't previously in OJS translation)
- Fixed the `{$revision}` / `{$fileRevision}` mismatch in `submission.event.fileUploaded` / `submission.event.fileRevised` (used preferred `{$fileRevision}`)
- The file's localized name was added for the missing `{$name}` variable to the above two keys
- Added upgrade script to rename `article_id` settings in `event_log` to `submission_id` instead

**Comment by ptrckb** [comment]
> - Added upgrade script to rename article_id settings in event_log to submission_id instead

Upgrading from a 2.4 installation, the `${submissionId}` are still not replaced in log entries.

Isn't it supposed to be `articleId` and `submissionId`?

**Comment by asmecher** [comment]
@ptrckb, is that `${submissionId}` or `{$submissionId}`?
