### ISSUE TITLE
Current Roles listing and user rights are not transparent 

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#2849]
OJS 3.0.2.

Under Users&Roles settings there is a listing of existing user roles within the context.

Besides showing the names of the roles the listing shows the four stages of the workflow and corresponding checkboxes which visualize the stages where the given role can gain access.

Or, that is what you would think.

However, although for example the role “production editor” has stage assignment checkboxes on Copyediting and Production by default, those checkboxes do not really mean anything.

A Production Editor can access a review stage of any submission. A Production Editor can even send a submission from the submissions stage to the review stage without being assigned to the submission although, by common sense, she should not have even access to either.

This all is extremely misleading for the editors. When they assign that role to someone, they expect that the checkboxes there actually matter.

What really counts here is the Permission level and the system does not show that at all in the listing. You have to know it is there or start to edit the role to show the pull down menu where it is mentioned.

The suggestions:
- The role listing should show the **permission level** of each role and maybe even explain somewhere on the page what it actually means.
- The stage assignment checboxes should actually affect also the journal manager level users **OR** they should be removed altogether from the journal manager level user roles.

Posted this also to the forum: https://forum.pkp.sfu.ca/t/current-roles-listing-and-user-rights-are-not-transparent/34126

**Comment by asmecher** [comment]
@ajnyga, I think the problem here is that full Editor roles (production editor, editor, manager) can access any submission at any time.

Two options:
- Make the checkboxes forced-on and disabled for any full editor role, or
- Instate access checks for full editors per the checkboxes.

I would lean towards the first fix, but it'll depend on whether this suits your workflow. Generally I lean towards using "sub" editor roles (e.g. section editors) for limited access.

**Comment by ajnyga** [comment]
Hi @asmecher 

Yes, the unlimited access together with the checkboxes are the source of the confusion.

**Option 1** would help a lot and make the journal manager level role permissions more clear. I think that in some lower roles there were some disabled selections as well.

**Option 2** would open up new possibilities and with some work would solve the central problem with journal manager level roles: https://forum.pkp.sfu.ca/t/new-role-permission-level-to-to-solve-a-central-problem-in-ojs/29030. That would require at least two new selections to that role grid besides the workflow stages: "Users&Roles" and "Log in as". You could then create an editor level role and prevent it from accessing Review stage, Users&Roles and use "Log in as" feature. This editor would just assign work and if needed would have a section editor role as well to enable her access some review stages as well - just not all to prevent "the all seeing eye".

I know, a lot of work **but** a solution to a long standing problem.

**Comment by asmecher** [comment]
@ajnyga, option 1 is a single line of code, so I've implemented it for the 3.1 release. I'll leave this issue option for the more considered approach, which I do think is promising.

**Comment by asmecher** [comment]
One line of code and I got it wrong. Fixed.

**Comment by ajnyga** [comment]
I do not think that the one line will be enough.

If I understand correctly, it will still show the old selections. For example the default Production Editor will have those two checkboxes selected. And when creating a new editor level role, you can still select the stages and also edit them by editing role. The grid just will not work.

We would need:
- either hide or force select stage settings when creating/editing a new journal manager role
- disable the selection in the grid (check, but maybe we should use the getForbiddenStages?) and always have them active
- In 3.1 upgrade, a sql that will change the journal manager role's settings so that all checkboxes get checked. Now, this will probably raise some questions in the forum. I have a feeling that there are some journals using for example the Production Editor role, but have not realized that the production editor actually works exactly the same as an ordinary editor.

----

A related issue to the grid is that I have come across at least four cases where an editor has deselected the review stage for the author role. They have thought that having that checked will let authors see the reviewers. I do not know how, but somehow the grid should show more clearly that the selections are different for different permission levels.

**Comment by ajnyga** [comment]
@asmecher, I was thinking something like this: https://github.com/pkp/pkp-lib/pull/2866

**Comment by ajnyga** [comment]
I am not particularly good in this, but maybe something like this:
```
<query>DELETE FROM user_group_stage WHERE user_group_id IN (SELECT DISTINCT user_group_id FROM user_groups WHERE role_id = '16')</query>
<query>INSERT INTO user_group_stage (context_id, user_group_id, stage_id) SELECT context_id, user_group_id, '1' FROM user_groups WHERE role_id = '16'</query>
<query>INSERT INTO user_group_stage (context_id, user_group_id, stage_id) SELECT context_id, user_group_id, '3' FROM user_groups WHERE role_id = '16'</query>
<query>INSERT INTO user_group_stage (context_id, user_group_id, stage_id) SELECT context_id, user_group_id, '4' FROM user_groups WHERE role_id = '16'</query>
<query>INSERT INTO user_group_stage (context_id, user_group_id, stage_id) SELECT context_id, user_group_id, '5' FROM user_groups WHERE role_id = '16'</query>
```

**Comment by ajnyga** [comment]
This is not included in the pr above, but adding the permission level to the grid could make it more clear.
![show_permission_levels](https://user-images.githubusercontent.com/16347527/31588884-04fa2454-b201-11e7-91c0-a7dcfbea5e7b.png)

**Comment by asmecher** [comment]
(Chucking into OJS 3.1.1. The [extremely expedient](https://github.com/pkp/pkp-lib/issues/2849#issuecomment-336593910) partial fix got included in 3.1.0 but the rest needs work.)

**Comment by ajnyga** [comment]
If the concept above is acceptable I can do additional changes.

I do think that showing the permission level in the grid would a good addition anyway. It would surface the permission level behind the role, which is very important to understand.

**Comment by asmecher** [comment]
Absolutely, please go ahead!

**Comment by ajnyga** [comment]
An updated pr here https://github.com/pkp/pkp-lib/pull/3018

**Comment by asmecher** [comment]
Merged -- thanks, @ajnyga!

**Comment by ajnyga** [comment]
Thanks @asmecher 
I think we still need some new sql to the upgrade that introduces this change, see https://github.com/pkp/pkp-lib/issues/2849#issuecomment-336726942

**Comment by ajnyga** [comment]
Just reminding @asmecher
I think we still need some new sql to the upgrade that introduces this change, see #2849 (comment)

**Comment by ajnyga** [comment]
This came up on the forum. Just a reminder @asmecher that this still need the upgrade sql mentioned here: https://github.com/pkp/pkp-lib/issues/2849#issuecomment-336726942

The problem is the "Production editor" who has by default access to just copyediting and production, but because the role has the Journal Manager permission level, users with that role can access everything (right?). So that is very potentially a cause of confusion for journals.

**Comment by librariam** [comment]
I hope it's ok for me to re-open this. A hosted client brought up the discrepancy between the Production Editor access level (JM = all) and the checkboxes that only show they should have access to Copyediting and Production. It looks like the fix was not finalized?

**Comment by ajnyga** [comment]
Yes, we need an addition to the OJS upgrade script I have described above.
