### ISSUE TITLE
[OJS] TinyMCE can't upload an image

### ISSUE THREAD

**Issue by t4x0n** [pkp/pkp-lib#3064]
Hi, 
I found an issue in OJS 3.1, I can not upload an image to a Custom Block (edited: in all TinyMCE):

I'm here trying to upload a little 2 Kb image, but:
![image](https://user-images.githubusercontent.com/5422984/32817671-d026e2f8-c99d-11e7-8023-d841b06c01d2.png)

next, the message about some error:
![image](https://user-images.githubusercontent.com/5422984/32817676-dd29eec8-c99d-11e7-97a5-2d46d45dbd60.png)

but script output is empty:
![image](https://user-images.githubusercontent.com/5422984/32817692-ed340b8c-c99d-11e7-8c08-cd7d11c3ad3d.png)

I hope this report helping you!  thanks!

**Comment by t4x0n** [comment]
really is in all TinyMCE textarea

**Comment by bozana** [comment]
@t4x0n, could you try to clear/delete your cookies? -- Maybe it is related to this issue: https://github.com/pkp/pkp-lib/issues/1919, that is fixed, but before working the old/wrong cookies have to be removed... Maybe...

**Comment by t4x0n** [comment]
@bozana I try with Firefox, Safari and Chrome in Mac but this is not the problem, even I try to change the permission folder to 777 but still not working

**Comment by t4x0n** [comment]
update: now just OJS 3.1 upgrade from 2.8.4 is the unique with this issue. I don't know how, but others two installations were fixed themselves

**Comment by t4x0n** [comment]
Well, I finally can upload an image in OJS 3.1 upgraded from 2.8.4 version... I just needed to add the "site" folder inside "public" folder (for some reason, this was not automatic)

**Comment by israelcefrin** [comment]
Hi @bozana I am facing this issue (no site folder inside public) with fresh installs. 
I've fixed it manually creating such folder, but AFAIK it should work out of box when deploying new installs, isn' t?
Should I file a new issue or keep conversation on this one?

Cheers!
