### ISSUE TITLE
[OJS 3.1.0-1] Desisting from adding a new discussion leaves behind an empty discussion

### ISSUE THREAD

**Issue by pkel** [pkp/pkp-lib#3385]
On an OJS 3.1.0-1 instance installed from release on PKP website, I can generate empty (ugly) discussions by pressing 'Add Discussion' and then closing the form without entering anything.

![a](https://user-images.githubusercontent.com/11337857/36256779-9ee1bab0-1254-11e8-8b88-abe107c4eaaf.png)
![b](https://user-images.githubusercontent.com/11337857/36256780-9f089ec8-1254-11e8-9aee-48924f733469.png)

**Comment by pkel** [comment]
Small addition for reproduction: A page refresh is needed to make the empty discussion show up.

**Comment by asmecher** [comment]
@pkel, what roles does your user have? Are they assigned to the submission under "Participants"?

**Comment by pkel** [comment]
@asmecher, I have  all roles except Administrator and am assigned to the submission as Journal Editor. There are two more Journal Editors and one Author.

**Comment by bozana** [comment]
Hmmm... for some reason I cannot reproduce this using the current ojs-stable-3_1_0 branch: e.g. as author, after a submission, I try to do that and I do not see that empty discussion... 
I also know this was a problem earlier but I thought we have fixed it...

**Comment by asmecher** [comment]
I can't reproduce it either -- we've had a few cases where this happened and I think they were related to two issues:
- Access policies preventing the user in question from deleting the placeholder discussion, or
- Missing CSRF tokens in the deletion request.

@pkel, if you watch your web developer toolkit's request list when you close the pop-up for creating a new discussion, you should see it send a request to delete that discussion. Can you check that this request exists, and see what the server response looks like?

**Comment by pkel** [comment]
After pressing **Add Discussion** I can see three requests. I list url followed by response.

```
/$$$call$$$/grid/queries/queries-grid/add-query?submissionId=3370&stageId=3&_=1519122561604
{"status":true,"content":"<ommited>","elementId":"0","events":null}
```

```
/notification/fetchNotification
{"status":true,"content":"","elementId":"0","events":null}
```

```
/$$$call$$$/grid/files/query/query-note-files-grid/fetch-grid?queryId=5762&noteId=6472&submissionId=3370&stageId=3&_=1519122561605
{"status":true,"content":"<omitted>","elementId":"0","events":null}
```

and after pressing the **X**: 

```
$$$call$$$/grid/queries/queries-grid/delete-query?queryId=5762&submissionId=3370&stageId=3
{"status":false,"content":"","elementId":"0","events":null}
```

**Comment by asmecher** [comment]
Ah, I see that the CSRF token is missing. I think this is already noted/fixed at https://github.com/pkp/pkp-lib/issues/3167 -- please try the patch there and see if it resolves the problem.

**Comment by pkel** [comment]
Problem resolved by patch from #3167. Thanks.

**Comment by forgive38** [comment]
Sorry to re open this issue, but I think it's not solved///

I think CSRF token is missing for query note delete request :
https://github.com/pkp/pkp-lib/blob/5180957c5408afa9ce9f65a00483ff27a26abcc1/templates/controllers/grid/queries/form/queryNoteForm.tpl#L17

Maybe just add csrfToken=$csrfToken here too works. I will try and make a PR.

**Comment by asmecher** [comment]
@forgive38, good spotting -- I thought we'd gotten the last of these. Merged https://github.com/pkp/pkp-lib/pull/3438 and cherry-picked to the `master` branch.
