### ISSUE TITLE
[OJS] Institutional Subscription creation form "domain" field requirements need minor tweaking

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#3439]
This only happens if someone makes an error in filling out the Institutional Subscription form. 

If an institutional subscription creation form is incorrectly submitted, for example if the IP addresses are poorly formatted and the user is returned to the form with an error telling them to fix them, the form subsequently requires that the Domain field be filled out, even if there are IP addresses in the other field. 

The form works normally on the first pass if the user gets all info correct; the workaround for now, if a user finds themselves having to re-fill the form, would be to close and reopen the form. But it would be nice not to have to do this.

**Comment by AndrewSwann** [comment]
Note this is seen on OJS 3.1.1.2 .   The error means loosing all entered data if there is a mistake in the IP addresses.  Better feedback on IP errors would also be desirable, particularly when there are many lines of these addresses.

**Comment by asmecher** [comment]
@AndrewSwann, this entry should fix that issue: https://github.com/pkp/pkp-lib/issues/4788

**Comment by librariam** [comment]
We are running 3.1.2-1 and the error is still happening, as reported by one of our journals. Replication steps are similar to those described by James:

![SR_step 1](https://user-images.githubusercontent.com/45104797/67499254-c5ec7200-f64e-11e9-8c90-76f90784ecbd.jpg)

![SR_step 2](https://user-images.githubusercontent.com/45104797/67499263-cb49bc80-f64e-11e9-8fa5-1f6c8e7869e9.jpg)

Thank you!

**Comment by asmecher** [comment]
@librariam, thanks for spotting this -- https://github.com/pkp/ojs/commit/7ae59920f210fc7848981526874bb2c046fe2597 should fix it.
