### ISSUE TITLE
OJS Non-expiring subscription type does not work

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#3483]
Hi @asmecher,

OJS 3.1.0.1

If you create a continuous subscription type in OJS3, two problems occur:
1. It is not possible to add a new subscription with that type without giving the dateStart and dateEnd dates in the form, but at the same time the dates are not stored: https://github.com/pkp/ojs/blob/master/classes/subscription/form/SubscriptionForm.inc.php#L190

2. When you give the dates and effectively should have created a non-expiring subscription, the user can not access any articles that are behind an embargo. The subscription block does show that there is a active subscription.

**Comment by mczirfusz** [comment]
I can also confirm this. 
IP access also does not work for non-expiring institutional subscriptions.

**Comment by asmecher** [comment]
@ajnyga and @mczirfusz, can you confirm whether this is still an issue with the latest stable release?

**Comment by mczirfusz** [comment]
[OJS 3.1.1.2 - sorry we did not upgrade yet to the latest release]
I checked @ajnyga 's point 1: I cannot give a person a non-expiring subscription without typing in a start and an end date. If I type in dates, these are not stored.

**Comment by asmecher** [comment]
The attached patches (equivalent, but made against different branches) should resolve it. You may also need to patch pkp/pkp-lib#4216.

**Comment by jnugent** [comment]
Hey @asmecher, hate to bring up an old closed issue, but this particular issue is still a problem for non-expiring institutional subscriptions, in 3.2.1-2.  We've a hosted client that recently upgraded to OJS3, and their non-expiring institutional subscriptions cannot be edited because the start and end dates are required in the `templates/payments/institutionalSubscriptionForm.tpl` template, but saving the form with those fields filled in generates a server side form validation error because non-expiring subscriptions cannot have date ranges.

**Comment by asmecher** [comment]
@jnugent, I suspect that's https://github.com/pkp/pkp-lib/issues/6510, which is fixed in 3.2.1-3.

**Comment by jnugent** [comment]
Ah thanks!  I'll use that!
