### ISSUE TITLE
Distribution Settings do not save

### ISSUE THREAD

**Issue by amandastevens** [pkp/pkp-lib#4497]
Testing pre-release of OJS 3.1.2, there are errors in Distribution Settings.  When I changed the settings under the Access tab and Payments tab and pressed save, the changes did not save.  When I changed them again and pressed save, the settings I previously tried to save were saved.  This occurred when trying enable payments, and it was only after enabling payments twice that the Payments menu appeared.

**Comment by asmecher** [comment]
There's a nav quirk where the whole page should reload when you save the payment settings. (This is already improved in the `master` branch by the setup forms rewrite.) Did this reload happen? That's when the "Payments" sidebar item should appear.

**Comment by amandastevens** [comment]
The page reloads each time you hit save, but the changes do not save or are not displayed in the reload.  They save the second time you change them (to what you changed them to the first time).

**Comment by asmecher** [comment]
Is it possible that there's a problem with file permissions in the `cache` subdirectory? Do you have trouble with other settings not "sticking", or just this one?

**Comment by asmecher** [comment]
Also, this may have been fixed already with https://github.com/pkp/pkp-lib/issues/4489 -- make sure the checkout is up to date with the fix committed there.

**Comment by asmecher** [comment]
@amandastevens, did you have a chance to verify this?

**Comment by amandastevens** [comment]
It still happens for me, only in Access Settings.  When I save changes in Workflow Settings, Website Settings, etc. I get a little green message saying "your changes have been saved," but I don't get this in Access Settings and the changes don't save.  

I don't know how to check if all the latest fixes were applied to the test install I'm using.

**Comment by asmecher** [comment]
@jmacgreg, can you confirm whether anyone updated that installation since Feb 13? If not, I think we can close this one.

**Comment by jmacgreg** [comment]
Hi both - the installation had been updated on the 22nd. I just re-updated it (and ran composer update / updated npm / cleared the cache), and the problem is still there.

**Comment by asmecher** [comment]
@jmacgreg or @amandastevens, would you mind PMing me the URL of the install?

**Comment by amandastevens** [comment]
I will send it

**Comment by asmecher** [comment]
Phew, this was a tricky one. The Zend opcode cache was caching the updated settings for up to 1 second after they were updated, so the refresh was seeing old settings as long as it completed within that time. I've added an opcode cache flush to the file caching code when that function is available.

**Comment by asmecher** [comment]
The sandbox install is patched and tests OK.

**Comment by jmacgreg** [comment]
Sweet! Thanks! Sounds like a super-weird one.

**Comment by ajnyga** [comment]
that explains a lot: https://github.com/pkp/pkp-lib/issues/3493#issuecomment-374276992
(had this problem in XAMPP installs but could not figure out why)

**Comment by asmecher** [comment]
It would be even more satisfying if I hadn't already closed that issue :)
