### ISSUE TITLE
[OJS] orcidProfile Plugin: ORCID integration in User Register form broken

### ISSUE THREAD

**Issue by isgrim** [pkp/pkp-lib#4601]
Hi everyone and especially @Vitaliy-1 ,

@asmecher send an error message via teampkp Slack and I found out, that in 3.1.2 the [orcidProfile Plugin](https://github.com/pkp/orcidProfile) integration with the User Registration form is completely broken.

* Pre-fill of the form fields is not working because of the name changes
* the hook for "registrationform::execute" is also broken because of changes to the execute function signature of the form. I still have no idea how to access the user in this hook, because now the local "$user" variable wont get passed to the "parent::execute" call, which in turn calls the hooks.

I probably need some help in fixing this, as I am also working on other stuff.
Just wanted to put that issue out there, so that the bug is known.

Greetings from Heidelberg,

Nils

**Comment by Baytan** [comment]
I was also going to open an issue about this. We just upgraded to OJS 3.1.2. Some authors of our journal complain that they cannot register to the journal as new user. After I disabled the Orcid plugin, registering can be made.
Interestingly, when Orcid plugin is enabled, I cannot assign articles to issues. When I disable it, I can.

Thanks for the contributors of the OJS. Best regards.

**Comment by isgrim** [comment]
> Interestingly, when Orcid plugin is enabled, I cannot assign articles to issues. When I disable it, I can.

This was fixed with an updated version which was made available yesterday, see this pull request https://github.com/pkp/orcidProfile/pull/62

**Comment by Baytan** [comment]
@isgrim 
Thank you for your interest and reply. I will look into it. However, user registration problem is still prevent use of this plugin for the time being. Regards.

**Comment by isgrim** [comment]
Yes, I am still thinking of a good solution to this, because there is another usability issue with user registration.
Currently the ORCID is also not stored as authenticated, because the access token is not submitted with the user registration, the whole registration process with the ORCID plugin needs more work, but I did not have more time to put into this.

**Comment by asmecher** [comment]
@isgrim, I fixed the name field population in https://github.com/pkp/orcidProfile/commit/54bd2e8843ddd5ed6bd575a330db921c0f288517, which was trivial so I've committed it to `stable-3_1_2` and `master`.

As for the hook behaviour change, I've opened a PR for that: https://github.com/pkp/orcidProfile/pull/66
Could you review this?

**Comment by asmecher** [comment]
As for `master`, I've committed pkp/orcidProfile@5d864b8 and e192a4d so that `$registrationForm->user` is exposed to the hook and picked up by the orcid profile plugin's hook registrant function.
