### ISSUE TITLE
Replace files in Publisher Library 

### ISSUE THREAD

**Issue by pmangahis** [pkp/pkp-lib#5780]
A hosting client has brought to our attention that there is no simple way for a Journal Manager to replace a file and keep the same URL.  

Deleting and re-adding the file causes the numbering at the end to change. The only way this can be done is by replacing the file in the backend in order to keep the URL the same. 

It would be ideal to keep the same URL if this is hyperlinked in different pages of the journal.

**Comment by asmecher** [comment]
See also https://forum.pkp.sfu.ca/t/ojs-3-2-0-2-are-files-in-publisher-library-automatically-renamed/60029/6; a URL slug might be helpful to add (along with a way to update existing files).

**Comment by amy-lyson** [comment]
There also needs to be a mechanism for hosting client like me to **replace** the file. In the publisher library, I can delete the old version, but not replace the file. That's where the issue of the path changing comes in as far as the current system.

**Comment by ctgraham** [comment]
See also: #5239

**Comment by ctgraham** [comment]
I've added PRs for the file replacement function, but left the slug unimplemented.

**Comment by asmecher** [comment]
PRs:
- https://github.com/pkp/pkp-lib/pull/7218
- https://github.com/pkp/pkp-lib/pull/7219
- https://github.com/pkp/pkp-lib/pull/7220

(@ctgraham, dropping a summary of the relevant PRs into the issue here as above helps us track what needs reviewing/consideration -- especially when we're using PRs across several repos and branches, it's easy for something to get forgotten! Thanks, I'll have a look at these soon; working through my backlog.)

**Comment by asmecher** [comment]
@ctgraham, have each of these branch ports been tested?

**Comment by ctgraham** [comment]
The PR for 3.2 has developer and end-user testing.  The others do not.  The port to 3.3 was a clean cherry-pick; the port to `main` was manual re-application across the spaces/tabs conversion.

**Comment by asmecher** [comment]
Are you able to test the 3.3 and 3.4 (`main`) PRs? The move to 3.3 involved a substantial rewrite of file storage (though I'm not sure library files are as affected), and 3.4 includes a ton of changes around autoloading and DAOs. I'd be happy to guide any adaptation that's needed, but a smoke test to know where they stand now would be really helpful.

**Comment by ctgraham** [comment]
I don't yet have a RHEL environment with PHP 7.3 support, so it will be a bit until I can get these tested against 3.3 and 3.4.

**Comment by ctgraham** [comment]
Current PRs:
https://github.com/pkp/pkp-lib/pull/7606
https://github.com/pkp/pkp-lib/pull/7219
https://github.com/pkp/pkp-lib/pull/7220

**Comment by asmecher** [comment]
@ctgraham, just asking because these are labeled "draft" -- are these ready for review/testing/merging?

**Comment by ctgraham** [comment]
@asmecher , I just spoke with @wopsononock earlier today and asked for him to try these out in our pre-production 3.3 and 3.4 environment per your prior request.

**Comment by asmecher** [comment]
:+1: Thanks, let me know when we can jump in!

**Comment by NateWr** [comment]
Another request on the forum: https://forum.pkp.sfu.ca/t/replacing-the-file-in-the-publisher-library/71246/2

**Comment by librariam** [comment]
+1 from a PKP|PS client. Use case: updates to the article template that then require updating the file link in several hosted journals.

**Comment by ctgraham** [comment]
@wopsononock , had you confirmed the functionality on these PRs in 3.3 and main?

**Comment by wopsononock** [comment]
No, I must have forgot about it.  I'll give it a whirl today.

**Comment by wopsononock** [comment]
This worked in 3.3.  Inside the edit menu there is now a new Replace File option.  I was able to change the file without changing the url.

**Comment by asmecher** [comment]
@wopsononock, just to confirm, this is 3.3 *with https://github.com/pkp/pkp-lib/pull/7606 applied*, right?

**Comment by asmecher** [comment]
^ Scratch that, I see you've confirmed in the PR. I've merged the `stable-3_3_0` PR; that's pushing the limits of what I'd normally merge to a stable branch, but it is no-impact to existing users, so I went ahead.

@wopsononock / @ctgraham, the PR for the `main` branch will definitely need to be dusted off, though; can one of you take a look?

**Comment by ctgraham** [comment]
FWIW, I think the 3.3.0-11 milestone was accurate here; the issue remains open pending the merge into `main`, but the feature is present in 3.3.0-11.

**Comment by asmecher** [comment]
Thanks for the heads-up -- I've moved it back to -11.

**Comment by asmecher** [comment]
@ctgraham, just a reminder that this issue is still needing attention in `main` (probably post-3.4.0-0 at this point) and is likely to get forgotten sitting as it does on an older milestone.

**Comment by asmecher** [comment]
@wopsononock and @ctgraham, anything we can do to move this one forward?

**Comment by wopsononock** [comment]
I wanted to test these one more time, but then needed to rebuild my test environment. I'm hoping to get these out next week.

**Comment by asmecher** [comment]
:+1: Thanks, no rush, just doing the rounds!

**Comment by asmecher** [comment]
@wopsononock, thanks, I added a review to the `stable-3_4_0` PR. Can you address the issues there, sync the other PRs (we'll take PRs for `stable-3_3_0` and newer), and list the current PRs in a comment below? Then I'll get them merged. Thanks!

**Comment by asmecher** [comment]
Thanks, @wopsononock and @ctgraham! I've merged this and cherry-picked forward to `main`.
