### ISSUE TITLE
"Reload defaults" for language invalidates $contextPath variable in "for authors", "for readers", etc.

### ISSUE THREAD

**Issue by jmvezic** [pkp/pkp-lib#6467]
**Describe the bug**
When reload defaults is clicked/activated for a language, the variable $contextPath no longer resolves to the journal's context in translations, but rather converts to escaped text (for example: http://ipaddress/ojs/index.php%7B$contextPath%7D/about/submissions#authorGuideline instead of http://ipaddress/ojs/index.php/journalabbrv/about/submissions#authorGuideline. This is reproducible in the default templates for "for reader", "for authors", "for librarians". 

**To Reproduce**
1. Go to Settings, Website, Setup, Information and check out the links in the text editor (they're correct and $contextPath variable resolves)
2. Go to Settings, Website, Setup, Languages and reset defaults on a language 
3. Go back to Settings, Website, Setup, Information and check out the links in the text editor (now they're plain text "contextPath")
4. The links are also now invalid on actual web pages of information for authors and readers.

**What application are you using?**
 OJS 3.2.1-2

![chrome_Gd5oEeYOiw](https://user-images.githubusercontent.com/8355671/101913045-ca614a80-3bc2-11eb-9808-c0bd2fb4df89.png)

**Comment by asmecher** [comment]
@jmvezic, thanks for reporting -- if you apply https://github.com/pkp/pkp-lib/commit/459635c6dfd4a120e58f8f0f58435b836fb16866 in `lib/pkp`, that should resolve the issue. Please confirm if you're able!

**Comment by jmvezic** [comment]
The bug is still there in the latest version of 3.3 (master branch). It's now a bit different, though - now all the links in the editor just say "{$contextPath}" without the rest of the path. Attaching a screenshot. Links on the webpage itself are still invalid on reloading defaults, they are, for example:

http://ipaddress/journal1/index.php%7B$contextPath%7D/user/register

There is also a separate "issue" of translation which is missing one slash after index.php. Before reloading defaults for a language (while the links are still valid), you can see it goes like this:

http://ipaddress/journal1/index.phpdemojournal/user/register

I assume this should be fixed via Weblate?

![chrome_PlyOdBmpcZ](https://user-images.githubusercontent.com/8355671/102320047-12de8680-3f7c-11eb-904d-c6e2272c8f44.png)

**Comment by asmecher** [comment]
@jmvezic, are you sure the Reload Defaults button is having an effect here? If you try saving a conspicuous change to the "For Readers" entry, then hit Reload Defaults, does it revert that change?

**Comment by jmvezic** [comment]
@asmecher Yes, making a change before hitting the "reload defaults" does work (it doesn't revert the change), however the issue is I have about 50 journals which never changed the text of those entries from default, all of which now have invalid URLs after hitting reload defaults (to load in some new e-mail template translations).

**Comment by asmecher** [comment]
@jmvezic, I fixed the issue separately with the path being incorrectly formed when the journal is created (e.g. `http://ipaddress/journal1/index.phpdemojournal/user/register`, missing the `/` between `index.php` and `demojournal`): https://github.com/pkp/pkp-lib/issues/6495

I think what you're saying, though, is that Reload Defaults *isn't* having an effect on these settings. The fact that you can change the setting (in the database), then reload the defaults, then find that the changed setting has not reverted to the original form, confirms it. Do I understand correctly?

**Comment by jmvezic** [comment]
@asmecher, so that bit behaves correctly, yes. The changed setting remains the same, as it should.

The issue is when the default texts _aren't_ changed. So say journal managers don't want to change them - they think the default texts are just fine. Then later on they reload the language defaults and suddenly the links in those texts no longer work (because the variable no longer resolves to the journal abbr. - it's just plain text).

So the steps are as I described originally:

1. Have clean OJS installation
2. Leave the "for authors", "for readers", etc. texts as they were (default)
3. Reload language defaults
4. Links in those texts are no longer valid/ no longer work

**Comment by asmecher** [comment]
@jmvezic, I think this is actually just a leftover issue from the earlier couple of fixes (https://github.com/pkp/pkp-lib/commit/459635c6dfd4a120e58f8f0f58435b836fb16866 and https://github.com/pkp/pkp-lib/issues/6495) -- the "Reload defaults" feature doesn't interact at all with the settings you're looking at, and the `{$contextPath}` variable should never appear in the settings the way you're seeing them (but did because of the [earlier fix](https://github.com/pkp/pkp-lib/commit/459635c6dfd4a120e58f8f0f58435b836fb16866). When settings are installed into the database upon journal creation, parameters like `{$contextPath}` are replaced by the actual value, but any undefined variables are left as-is. You're seeing `{$contextPath}` because that variable wasn't defined when the journal was created, and there's no code in the system to replace it afterwards. Once you correct those manually, the problem shouldn't reappear.

**Comment by jmvezic** [comment]
Hi @asmecher, just tried the latest master commit and it does seem this is fixed. Thanks!

**Comment by asmecher** [comment]
Thanks, I'm happy to hear it!
