### ISSUE TITLE
Infinite scrolling is broken

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#656]
The data build tests barf when attempting to locate a submission as editor (dbarnes), because the expected .gridPagingScrolling element is not found. See:

https://github.com/pkp/pkp-lib/blob/master/tests/WebTestCase.inc.php#L385

This leads to the following from Selenium:

    ERROR: Element css=#activeSubmissionsListGridContainer .gridPagingScrolling not found

I don't think it'll be necessary to get the tests set up in order to fix this, but just in case, my tests_fix branches (both OJS and pkp-lib) are working up until this point.

@NateWr and @beghelli, maybe you two could take a look at this tomorrow (Friday)? Thanks!

**Comment by NateWr** [comment]
I dove into this today without luck. I can't figure out how `controllers/grid/feature/infiniteScrolling.tpl` (which includes that markup) is meant to get loaded into the grid. And if I just add it to `grid.tpl` it doesn't fix the infinite scrolling.

I decided to try to see what's changed from when it was working. But I went all the way back to start-of-May commits for ojs/pkp-lib and still the infinite scrolling wasn't working for me. Do you guys have commit hashes for ojs/pkp-lib where infinite scrolling on the active submissions grid is working?

**Comment by NateWr** [comment]
Woot! Should have looked in the javascript, of course.

(Note, infinite scrolling is still broken. This only restores the `.gridPagingScrolling` element for the test.)

**Comment by asmecher** [comment]
FWIW scrolling works for me on Firefox; @beghelli is checking it anyway.

**Comment by asmecher** [comment]
Note that submission lists show row counts ("5 of 18 Items") but these don't update with additional loads.

**Comment by beghelli** [comment]
Fixed.

**Comment by NateWr** [comment]
Hmm, still not loading new results for me. Must be something in my config. We'll see if anyone else has the problem I guess.
