### ISSUE TITLE
OMP 3.3 - Onix export failing due to class type mismatch

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#6604]
Apologies in advance for this one.  I know how convoluted the XML filter code is.  

Exporting submissions in ONIX format currently fails, because there is a class type mismatch in the filter code.   The filters have lots of assertion code to validate classes to ensure that the correct filter is being called with the correct input, and right now the class `lib/pkp/classes/filter/ClassTypeDescription.inc.php` calls `checkType` and is handed an `$object`.   The line:

`if (!is_a($object, $this->_className)) return false;`

is returning false because `$this->_className` is "Submission" whereas the `$object` being handed to it is "Monograph".  I no longer see any Monograph class in the codebase.

I think this is due to the `filterConfig.xml `file shipping with the ONIX plugin defining an inputType of:

`inputType="class::classes.monograph.Monograph"`

There hasn't been a Monograph class in OMP since 3.1.2 so I suspect that this may have been broken for a while.

**Comment by asmecher** [comment]
This is a leftover from https://github.com/pkp/pkp-lib/issues/5573 -- running the 3.2.x upgrade scripts will correct installs, but new installs will suffer the issue, which is probably why it wasn't reported until now. I'll tackle it.

**Comment by asmecher** [comment]
Actually, while I've fixed the mismatch listed above, it doesn't appear to have stopped things from working in this case -- what I suspect you're encountering is a more general lack of helpfulness on the plugin's part. If the submission doesn't include enough data to form a complete export and the generated XML would be invalid -- for example, if trying to export a submission that doesn't include a publication format.

I'm filing two related issues for cleanup:
- https://github.com/pkp/pkp-lib/issues/6609
- https://github.com/pkp/pkp-lib/issues/6610

However, please confirm that you're able to export a completed submission as the plugin currently stands -- barring a problem there, I'll close this issue.

**Comment by jnugent** [comment]
@asmecher  the fix to the filter lets the code proceed past the class comparison, but my export is still failing despite having a published monograph with (as far as I can tell) complete metadata and publication objects.  I'm investigating further.

**Comment by jnugent** [comment]
There's still something not quite right. If I turn on $returnErrors in the main Filter class, I get back an ONIX document that passes lint tests and seems valid.  However, the 

`$exportFilter->execute($submission);`

Call in the plugin class itself does not return $submissionXml.  There's another input/output comparison test that happens in 

`lib/pkp/plugins/importexport/native/filter/NativeExportFilter.inc.php`

in the `supports` method where the call:

`$validOutput = $outputType->isCompatible($output);`

is returning false. In my case, $output is a complete DOMDocument object, which should be correct, since $outputType is supposed to be an XMLTypeDescription based on the code.

As I said, this process seems to get circumvented if I explicitly set $returnErrors to true in the main Filter class.  

I think this is another database inconsistency.  This is a fresh install of OMP 3.3.

**Comment by jnugent** [comment]
Okay, so it is failing validation.  My error is:

Element \\'{http://ns.editeur.org/onix/3.0/reference}DescriptiveDetail\\': This element is not expected. Expected is one of ( {http://ns.editeur.org/onix/3.0/reference}RecordSourceIdentifier, {http://ns.editeur.org/onix/3.0/reference}RecordSourceName, {http://ns.editeur.org/onix/3.0/reference}ProductIdentifier ).

So I'll look and see what's up there, because as far as I can tell all of the Monograph fields are filled in.  As far as the other tickets go with respect to making the plugin more user friendly, one of the biggest problems is that the 

`./lib/pkp/classes/xslt/XMLTypeDescription.inc.php`
 
suppresses validation warnings in the `checkType` function here:

```
                                libxml_use_internal_errors(true);
                                $errors = libxml_get_errors();
```

but it never does anything with that` $errors `array.

**Comment by jnugent** [comment]
Fixed!  This can stay closed.  Thanks for bearing with me, @asmecher. It's not quite so obvious now that the "edit" link below the publication format contains a modal with the tabs for the rest of the metadata.  It's been a while since I've looked at the ONIX stuff!
