### ISSUE TITLE
tasks cannot be marked as read/unread or deleted

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#7450]
**Describe the bug**
In the task modal, tasks can be read and selected, but the buttons for marking them as new or read, or deleting them, no longer work.  This works fine in both a 3.3.0.3 and 3.3.0.6 installation we have, but not in two new 3.3.0.8 stable upgrades as of this morning.  Did this modal lose a JS handler perhaps?

**To Reproduce**
1. Click on the task icon to reveal the list of tasks,
2. Select a task by checking the box next to it
3. Attempt to mark it as read or delete it.
4. There is no network activity and no errors in the console.  

**What application are you using?**
 OJS 3.3.0.8 stable

![Screenshot at 2021-11-11 13-23-14](https://user-images.githubusercontent.com/218719/141341651-9ad2e3ec-da6a-4ddc-9dd8-d1ed1d7cbe90.png)

**Comment by asmecher** [comment]
The addition of some [CSRF checks](https://github.com/pkp/pkp-lib/issues/7371) resulted in a change to one of the JS handlers. If that change hasn't made it to the browser, you'll see what you describe. Make sure your compiled JS is up to date, and flush your browser cache.

**Comment by jnugent** [comment]
That's part of our regular deployment procedure, but yes, clearing my browser cache just now and rebuilding all of the javascript via npm still results in the same issue.

**Comment by asmecher** [comment]
This is the old (non-NPM) JavaScript; you build it using tools/buildjs.sh -- however I'm pretty sure I committed an updated compiled version in GitHub too. If that doesn't help, can you send me privately the URL of the journal in question?

**Comment by jnugent** [comment]
Even if I disable minified Javascript the problem persists here.  I've cleared everything again, same issue. I've sent you creds on slack.

**Comment by asmecher** [comment]
This commit will fix it (along with recompiled minified JS): https://github.com/pkp/pkp-lib/commit/e67b6e15236744d84e9491f50e277a9bd656a5ce

**Comment by jnugent** [comment]
Thank you, confirming fixed!
