### ISSUE TITLE
Cancelled reviews are included in a reviewer's "active" review count

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#8397]
**Describe the bug**
The Review Report plugin does not seem to consider cancelled review assignments as separate inactive reviews, so they get included in the active review total. The other queries in the query builder classes have been updated already to reflect this, so just a tweak needed here.

**Comment by jnugent** [comment]
It also occurs to me that the Review Report plugin may need an adjustment for this issue too.  I briefly looked at the DAO class included there and I don't see a mention of the "cancelled" column so reviews that are cancelled and do not have a date_completed set may be being included in other totals.

**Comment by asmecher** [comment]
@jnugent, are you sure you duplicated this in 3.3.0-13? It should have been fixed in 3.3.0-12: https://github.com/pkp/pkp-lib/issues/8189

**Comment by jnugent** [comment]
Dang, you're right, of course.  I was incorrect in my OJS version number.  

I still have a question about the review report plugin though - I don't see any mention of the cancelled flag in the query in the DAO.  Are cancelled reviews being included in active totals in that report?

**Comment by asmecher** [comment]
Yes, it looks like this issue still affects the review report plugin. Can you update the original entry to scope it for that?

**Comment by bozana** [comment]
@jnugent, would then here a new column 'Cancelled' containing 'yes' or 'no' be the solution?

**Comment by bozana** [comment]
PRs:
reviewReport stable-3_3_0: https://github.com/pkp/reviewReport/pull/42
ojs stable-3_3_0: https://github.com/pkp/ojs/pull/3650 (only submodule update)
omp stable-3_3_0: https://github.com/pkp/omp/pull/1268  (only submodule update)

**Comment by bozana** [comment]
@asmecher, could you take a look at the PRs?

**Comment by asmecher** [comment]
That looks good, @bozana -- please go ahead!
